education model fields
hack4impact-uiuc/mentee pull request #10
Opened 2020-10-01 22:39 UTC by Feeshay

## Status:

## Description :star2:

Fixes #number
 
## TODOs :star:

2020-10-01 22:48 UTC, chyku requested changes
small things

2020-10-01 22:48 UTC, chyku commented on backend/api/models/Education.py
> +class Email(EmbeddedDocument, Mixin):
rename this lol

2020-10-01 22:48 UTC, chyku commented on backend/api/models/Education.py
> +                    graduation date {self.graduationYear}>"""
3 quotes? Also include the class name here and have a colon after the field name like "majors: {self.majors}"

2020-10-01 22:52 UTC, Feeshay commented on backend/api/models/Education.py
> +class Email(EmbeddedDocument, Mixin):
f

2020-10-01 22:52 UTC, Feeshay commented on backend/api/models/Education.py
> +                    graduation date {self.graduationYear}>"""
3 quotes is for multiline strings but I could also just put everything into 1 line

2020-10-01 22:53 UTC, chyku commented on backend/api/models/Education.py
> +                    graduation date {self.graduationYear}>"""
oh lol oop

2020-10-02 23:42 UTC, Leundai requested changes
within init.py of the folder, models make sure to also include MentorProfile in there. like so. Not too sure if that is needed though
![image](https://user-images.githubusercontent.com/28935000/94977557-eec3eb00-04de-11eb-8ff7-602e40710af0.png)

2020-10-06 18:53 UTC, chyku requested changes

2020-10-06 18:53 UTC, chyku commented on backend/api/models/Education.py
> +    graduation_year = IntField()
Should also mark which fields are required (i.e. `title = StringField(max_length=200, required=True)`)

2020-10-06 20:00 UTC, chyku requested changes

2020-10-06 20:00 UTC, chyku commented on backend/api/models/Education.py
> +    majors = ListField(StringField(), min_length=1, required=True)
it's not necessary to put max and min lengths for every field, just that required is true for these

2020-10-06 20:20 UTC, chyku approved these changes
good stuff :book:

2020-10-06 20:24 UTC, Lam7150 approved these changes
beautiful, just like you Michael

2020-10-06 20:26 UTC, Leundai approved these changes
Awesome!

2020-10-06 20:31 UTC, merged