Login page
hack4impact-uiuc/mentee pull request #109
Opened 2020-11-26 02:49 UTC by Lam7150

## Status: :construction: In development

## Description :star2:
Creating sign in page on homepage
Two things to correct before deployment:
1. Login button size
2. Integrating this properly into the auth flow (structuring properly)

Fixes #92 
 
## TODOs :star:

2020-11-26 02:51 UTC, Lam7150 commented
@Feeshay For the login button, I'm not able to change the size of it (specifically height), is this intentional?
Would it be a good idea to add a height prop to the MenteeButton component, or implement it so it expands to the outer container? curious what you think Michael

2020-11-26 02:52 UTC, Lam7150 commented
also @Feeshay @chyku currently I made it in the Home.js just to get the css right, but what's the best place I should implement this component and integrate into the current structure for auth logic? 

I have some ideas, but curious what you guys think as you two are more knowledgeable on that aspect than me.

2020-12-03 06:28 UTC, AngelaLuo49021 requested changes
- the size of everything looks really really big and its kind of too in the face/overwhelming
- if you could shrink the white box by a little and also all the text inside it, that would be great. Also the bee can be shrunk by a little bit too. 
- if the above takes too long for product showcase, main things that are too large are the words "Sign In" and the email and password text box
![image](https://user-images.githubusercontent.com/42478474/100972257-214d8c80-34fe-11eb-8215-f0bbf62b443c.png)

2020-12-03 22:38 UTC, chyku requested changes
nits

2020-12-03 22:38 UTC, chyku commented on frontend/src/components/css/Login.scss
> +}
this css is kinda redundant since you can nest
```suggestion
.login-register-button {
    background: none;
    border: none;
    color: #E4BB4F;
    text-decoration: underline;
    margin-left: 5px;
    transition-duration: 0.4s;
    
    :hover {
          color: #ffe5a3;
    }
    
    :active {
          color: #E4BB4F;
     }
}
```

2020-12-03 22:38 UTC, chyku commented on frontend/src/components/css/Login.scss
> +}
also please add color constants to `frontend/src/components/css/_app.scss` and import to use variable

2020-12-03 22:38 UTC, chyku commented on frontend/src/components/css/MenteeButton.scss
> +  background: #E4BB4F;
same w adding the color `frontend/src/components/css/_app.scss`

2020-12-03 22:38 UTC, chyku commented on frontend/src/components/pages/Login.js
> +              onClick={() => console.log("clicked")}
console log?? get rid of that

2020-12-03 22:45 UTC, Feeshay commented on frontend/src/components/pages/Home.js
> +            <div
this got moved to the login page so shouldn't be a problem now

2020-12-04 18:52 UTC, chyku approved these changes
cool stuff

2020-12-04 18:54 UTC, Leundai approved these changes
beautiful

2020-12-04 20:21 UTC, AngelaLuo49021 approved these changes
gud

2020-12-04 20:23 UTC, merged