Videolinks model
hack4impact-uiuc/mentee pull request #11
Opened 2020-10-01 23:06 UTC by Leundai

## Status: :construction:

## Description :star2:
Adding VideoLinks model so that it can be used for the Mentor model
Fixes #8 
 
## TODOs :star:
- [ ] Model Review

2020-10-05 16:59 UTC, chyku requested changes
naming + technicalities

2020-10-05 16:59 UTC, chyku commented on backend/api/models/VideoLinks.py
> +        self.link = link
maybe URL would be better, link is somewhat of a vague name

2020-10-05 16:59 UTC, chyku commented on backend/api/models/VideoLinks.py
> +class VideoLinks(Document, Mixin):
We wanted this to be a EmbeddedDocument first but it might be better as a document, not sure if you did that intentionally lol

2020-10-05 16:59 UTC, chyku commented on backend/api/models/VideoLinks.py
> +class VideoLinks(Document, Mixin):
Also not sure if VideoLinks is the best name for this object- think about what it's representing. it's not just the link but a video + its URL + tag

2020-10-05 16:59 UTC, chyku commented on backend/api/models/VideoLinks.py
> +    tag = StringField(required=True)
Forgot to mention this but it may be helpful to track the title of the videos- we can discuss on Tues

2020-10-05 16:59 UTC, chyku commented on backend/api/models/VideoLinks.py
> +        return f"<VideoLink {self.link}>"
This is what prints out when you print the object, so you also want to print out the tag and everything that's inside. Also format this as <[ObjectName] field: {self.field}> etc

2020-10-05 19:51 UTC, Leundai commented on backend/api/models/VideoLinks.py
> +class VideoLinks(Document, Mixin):
I've got a couple of ideas VideoInfo, or simply just Video. Lmk if there is something better too! For now, I'll have it as VideoInfo

2020-10-06 18:49 UTC, chyku commented on backend/api/models/VideoLinks.py
> +class VideoLinks(Document, Mixin):
LOL I personally prefer Video because it's what it's representing in the app basically. Otherwise you could say that any DB collection could be [Object]Info so just [Object] is more concise

2020-10-06 19:56 UTC, Leundai reviewed
Ignore this

2020-10-06 20:30 UTC, chyku approved these changes
beautiful

2020-10-06 20:31 UTC, Lam7150 approved these changes
Looks good!

2020-10-06 20:40 UTC, merged