Thread chat
hack4impact-uiuc/mentee pull request #1113
Opened 2024-11-10 17:34 UTC by WebMon9099

## Status:

## Description :star2:

Add time zone
 
## TODOs :star:

2024-11-10 22:05 UTC, robert-dm requested changes
please check my comments

2024-11-10 22:05 UTC, robert-dm commented on frontend/src/components/pages/MenteeProfileForm.js
> -  const educationSubForm = () => (
@WebMon9099 why this block for educationSubForm was removed_

2024-11-11 00:28 UTC, WebMon9099 commented on frontend/src/components/pages/MenteeProfileForm.js
> -  const educationSubForm = () => (
No worries
That is unnecessary code that is not used in the mentee profile form.

2024-11-11 10:47 UTC, robert-dm approved these changes

2024-11-11 10:47 UTC, merged