Added mentor profile model
hack4impact-uiuc/mentee pull request #12
Opened 2020-10-01 23:13 UTC by AzureQDragon

## Status: :construction:

## Description :star2:

Fixes #9 
 
## TODOs :star:

2020-10-02 17:35 UTC, Leundai requested changes
within __init__.py of the folder models make sure to also include MentorProfile in there. like so
![image](https://user-images.githubusercontent.com/28935000/94952520-bb1b9d80-04ab-11eb-80f6-513148818bd4.png)

2020-10-02 23:37 UTC, Leundai approved these changes

2020-10-05 17:04 UTC, chyku requested changes
lookin good!!

2020-10-05 17:04 UTC, chyku commented on backend/api/models/MentorProfile.py
> +                \n offers_group_appointments: {self.offers_group_appointments}>"""
Run `black .` to format! Will be adding checks in later today for this

2020-10-05 17:04 UTC, chyku commented on backend/api/models/__init__.py
> +__all__ = ["db", "Email", "Person", "MentorProfile"]
there should be a newline between the imports and the definition of `__all__`

2020-10-05 17:04 UTC, chyku commented on backend/api/models/MentorProfile.py
> +    uid = "" # TBD later
make the comment a `# TODO: [thing you need to do]` for convention + description of the task!

2020-10-05 17:04 UTC, chyku commented on backend/api/models/MentorProfile.py
> +    specializations = ListField(StringField(required=True))
not sure how this exactly works with ListFields, but shouldn't the ListField itself be required, not the strings within it?

2020-10-06 18:52 UTC, chyku requested changes
Files

2020-10-06 18:52 UTC, chyku commented on .vscode/settings.json
> +}
this shouldn't be committed! Make sure you add this to `.gitignore` if it's not already

2020-10-06 18:52 UTC, chyku commented on frontend/package-lock.json
> +{
Did you end up using npm instead of yarn to install packages? Not sure why you'd end up having a package-lock

2020-10-06 20:56 UTC, chyku approved these changes
looks :+1:

2020-10-06 20:56 UTC, merged