Video Page Styling
hack4impact-uiuc/mentee pull request #133
Opened 2020-12-15 22:03 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #105 
To make this website responsive we must do. 

![image](https://user-images.githubusercontent.com/28935000/102277939-93ef3c80-3eee-11eb-96a3-f43fc1c9cc56.png)

## TODOs :star:
- [ ] Tests
- [ ] Documentation

2020-12-19 19:24 UTC, AngelaLuo49021 requested changes
Can you bold the video title and increase the space between the video icon and the text a little bit? Also if the pin could be moved a bit more away from the border that would be great but not a big deal
![image](https://user-images.githubusercontent.com/42478474/102697684-4d0a8b00-41fd-11eb-9d8f-03a1e543b2fd.png)
![image](https://user-images.githubusercontent.com/42478474/102697691-585db680-41fd-11eb-96ca-393ab3c26cf6.png)

2020-12-23 01:42 UTC, AngelaLuo49021 approved these changes
Very cool style changes, looks good!

2020-12-28 02:31 UTC, chyku commented on frontend/src/components/pages/Videos.js
>        setName(mentor.name);
should include this in the if (mentor) block- if there is no mentor mentor.name is also nothing?

2020-12-28 02:31 UTC, chyku commented on frontend/src/components/pages/Videos.js
> +        }
why is it necessary to use a for loop instead of foreach?

2020-12-29 20:29 UTC, chyku approved these changes

2020-12-29 21:30 UTC, merged