Yarn commands for dev/formatting
hack4impact-uiuc/mentee pull request #136
Opened 2020-12-15 22:18 UTC by Leundai

## Status: :rocket: Ready

## Description :star2:

![image](https://user-images.githubusercontent.com/28935000/102279524-2abcf880-3ef1-11eb-805c-52909c625cc4.png)

## TODOs :star:

2020-12-16 20:38 UTC, chyku commented
i appreciate this but this is lower priority than our feature/bug issues :sob:

2020-12-29 22:19 UTC, chyku requested changes
pls add documentation to a readme somewhere that's all i request

2020-12-29 22:19 UTC, chyku commented on backend/Makefile
> +format:
LMAO good on u for finding this file, if you couldn't tell it's not updated from the original code we repurposed for mongodb

2021-01-02 14:54 UTC, chyku approved these changes

2021-01-02 19:30 UTC, AngelaLuo49021 approved these changes
kool

2021-01-02 20:19 UTC, merged