Mentor email notifications
hack4impact-uiuc/mentee pull request #141
Opened 2020-12-18 03:11 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #112 

Uses SendGrid as a method to send new emails.

This is ready and is working for now. All I need is to use the actual email instead of my own. I also need Leticia to verify her email for me through SendGrid so that it's ready for production.

## Images

### Proof of working emailing
![image](https://user-images.githubusercontent.com/28935000/102569819-cb571800-40ab-11eb-90aa-9fafc97f41c8.png)

### Appointment response
![image](https://user-images.githubusercontent.com/28935000/102569896-e9247d00-40ab-11eb-9a9f-9f39ed4348a0.png)

### Updated Database
![image](https://user-images.githubusercontent.com/28935000/102569970-09543c00-40ac-11eb-8c4d-3049eac4e260.png)

 
## TODOs :star:
- [ ] Tests
- [ ] Documentation
- [ ] Create a better email format

2020-12-28 05:55 UTC, AngelaLuo49021 approved these changes
Good stuff!
Hopefully we can switch out the email to the official one before this gets merged

2020-12-29 22:23 UTC, chyku requested changes

2020-12-29 22:23 UTC, chyku commented on backend/api/utils/constants.py
> +APPT_NOTIFICATION_TEMPLATE = "d-bd3cb0c88bc94c5babf9280ea7a13aed"
ohh is this a template id on sendgrid?

2020-12-29 22:23 UTC, chyku commented on backend/api/utils/constants.py
> +SENDER_EMAIL = "leogalindofrias@gmail.com"
would be helpful to write some docs/instructions for adding Letitia's email instead?

2020-12-29 22:23 UTC, chyku commented on backend/api/views/appointment.py
> +        return create_response(status=422, message=msg)
not sure if this status should be 422, 422 suggests user error when it might not be so here

2021-01-01 22:12 UTC, Leundai commented on backend/api/utils/constants.py
> +APPT_NOTIFICATION_TEMPLATE = "d-bd3cb0c88bc94c5babf9280ea7a13aed"
Yessir

2021-01-01 22:17 UTC, Leundai commented on backend/api/views/appointment.py
> +from ..utils.constants import APPOINTMENT_EMAIL_MESSAGE, APPT_NOTIFICATION_TEMPLATE
im a goof bro

2021-01-01 22:18 UTC, Leundai commented on backend/api/utils/constants.py
> +SENDER_EMAIL = "leogalindofrias@gmail.com"
Before this gets merged we want to add Letitia's email so that mine isn't attached there lol. But I'll add some documentation on how to change it

2021-01-02 14:59 UTC, chyku commented on backend/api/utils/constants.py
> +SENDER_EMAIL = "leogalindofrias@gmail.com"
yee i also think it could be safer or just nicer to have this also be an environment variable, we don't want to be exposing people's emails on github if they don't want it exposed

2021-01-02 15:00 UTC, chyku approved these changes
coolio

2021-01-03 04:49 UTC, merged