View Details On Upcoming Appointment
hack4impact-uiuc/mentee pull request #144
Opened 2020-12-28 06:00 UTC by nroy20

## Status: 🚀 

## Description :star2:

Fixes #130
 
## TODOs :star:

2020-12-28 18:26 UTC, Leundai reviewed
Good stuff just some minor changes! 👍

2020-12-28 18:26 UTC, Leundai commented on frontend/src/components/AppointmentInfo.js
> +import React, { useState } from "react";
useState can be removed since it isn't being used here

2020-12-28 18:26 UTC, Leundai commented on frontend/src/components/AppointmentInfo.js
> +import React, { useState } from "react";
Same with "antd" Button

2020-12-28 18:26 UTC, Leundai commented on frontend/src/components/pages/Appointments.js
> +  CommentOutlined,
I think you can remove everything except for `ClockCircleOutlined` and `InfoCircleFilled` since the others aren't used anymore

2020-12-28 18:26 UTC, Leundai commented on frontend/src/components/AppointmentInfo.js
> +    }
This might not be needed since if there is nothing to return it'll just be null

2020-12-29 20:35 UTC, AngelaLuo49021 requested changes
Combined your old PR with this one so now you just have one

Issue with CSS, can you make the box longer when a field is really long and could overlap?
![image](https://user-images.githubusercontent.com/42478474/103312476-c87cf100-49e2-11eb-881a-da7a957e6cdc.png)

for this one just add a character count limit and put "..." to cut it off
![image](https://user-images.githubusercontent.com/42478474/103312514-efd3be00-49e2-11eb-983c-5b19fb631209.png)

Last thing, for the column of past appoitnments, when they click on it, do the same pop up that you did for accepted appointments without the button. They can just click anywhere in the box since we dont have an icon

2020-12-29 21:22 UTC, AngelaLuo49021 reviewed
Just a note: 
We need to show if the mentee says they will allow calls or texting (design changes)
![image](https://user-images.githubusercontent.com/42478474/103316735-07b13f00-49ef-11eb-8e64-04741559a011.png)

We need to remove ethnicity

2020-12-29 22:56 UTC, nroy20 commented on frontend/src/components/AppointmentInfo.js
> +    }
without null it puts default buttons instead of no buttons

2021-01-21 19:58 UTC, AngelaLuo49021 requested changes
Add some padding on the bottom of the modal 
![image](https://user-images.githubusercontent.com/42478474/105405356-b14fae80-5bf0-11eb-9f50-86db8a4e1e28.png)
Also fix the overlapping between names and the other fields 
![image](https://user-images.githubusercontent.com/42478474/105405451-c88e9c00-5bf0-11eb-8467-94ea051b42e8.png)

2021-01-26 04:04 UTC, AngelaLuo49021 approved these changes
Very cool

2021-01-26 04:13 UTC, chyku approved these changes
speedy approve from me

2021-01-26 04:13 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +                    email={appointment.email}
why isnt the entire appt passed in here as a prop instead of its individual fields

2021-01-26 04:13 UTC, chyku commented on frontend/src/utils/dateFormatting.js
> +      email: appointment.email,
the spread operator might help here

2021-01-26 17:31 UTC, merged