added model and verify endpoint
hack4impact-uiuc/mentee pull request #145
Opened 2020-12-29 19:57 UTC by Leundai

## Status: :rocket: Ready

## Description :star2:

Fixes #119 
 
## Screenshots
![image](https://user-images.githubusercontent.com/28935000/103309928-03c7f180-49dc-11eb-952e-7554056a06de.png)

![image](https://user-images.githubusercontent.com/28935000/103310080-59040300-49dc-11eb-8f7a-810a1ce330e3.png)

![image](https://user-images.githubusercontent.com/28935000/103310380-1131ab80-49dd-11eb-81de-301aa5b73938.png)

## TODOs :star:
- [x] Tests
- [x] Screenshots

2020-12-29 21:40 UTC, AngelaLuo49021 approved these changes
Looks good to me!

2020-12-29 22:26 UTC, chyku requested changes
lgtm except for the name of the endpoint?

2020-12-29 22:26 UTC, chyku commented on backend/api/views/main.py
> +@main.route("/verifyAccountCreation", methods=["GET"])
if this is just for registration ignore this comment but we also want to verify access for mentees when they're trying to search for mentors and make appointments (i think), so this url should be more broad to be that we're just verifying emails here

2020-12-29 22:26 UTC, chyku commented on backend/api/models/VerifiedEmail.py
> +    is_mentor = BooleanField(required=True)
dont change anything here but something worth thinking about is whether there could be more types of users with email verification in the future in which case this field wouldn't be scalable to that

2021-01-02 14:57 UTC, chyku requested changes
SORRY i literally always miss things on the first review but just a note here

2021-01-02 14:57 UTC, chyku commented on backend/api/views/verify.py
> +        status=200,
for consistency for all the responses, could you add the `is_verified` field to all 3 and have it be false when something fails? something to think abt during API design is how u want the responses to look & what the frontend will check for success or failure, this could be either or both status codes or data returned.

2021-01-05 23:10 UTC, merged