Lock Mentor Gallery
hack4impact-uiuc/mentee pull request #151
Opened 2021-01-01 05:20 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #137 
 
## TODOs :star:
- [ ] Tests
- [ ] Documentation

2021-01-06 03:52 UTC, Leundai commented on frontend/src/components/MenteeVerificationModal.js
> +  };
I'm not too sure if this is the right way to handle this. Since I am creating a whole separate file that is also async which calls the endpoint.

2021-01-09 19:53 UTC, AngelaLuo49021 requested changes
The modal doesn't pop up when clicking the top right "find a mentor" button but everything else looks great!
#138 is basically the same thing but the modal pops up before they book an appointment. Could this be taken care of in the same PR?

2021-01-09 21:48 UTC, Leundai commented on frontend/src/components/MenteeVerificationModal.js
> +      />
I'm not really liking how the modals are being handled with verification. So before this gets merged I'm going to be moving some stuff around so that verification is cleanly integrated into the buttons but also so that it is scalable with other types of scenarios.

2021-01-18 19:03 UTC, chyku requested changes
very very small things, great work :100:

2021-01-18 19:03 UTC, chyku commented on frontend/src/utils/verifyMentee.js
> +  return Boolean(JSON.parse(sessionStorage.getItem("isVerified")));
are we still using session storage here? i don't think i saw any code storing it into the session storage

2021-01-21 18:06 UTC, Leundai commented on frontend/src/utils/verifyMentee.js
> +  return Boolean(JSON.parse(sessionStorage.getItem("isVerified")));
nah it is just unreachable code since it isn't used anywhere. I'll remove it

2021-01-21 19:32 UTC, Leundai commented on frontend/src/components/css/MenteeButton.scss
> -  border-radius: 13px;
they might. I put them back to be safe

2021-01-21 19:40 UTC, chyku approved these changes
lgtm

2021-01-21 19:54 UTC, AngelaLuo49021 approved these changes
Looks great!

2021-01-21 20:19 UTC, merged