Fix FIelds on Appointment Request
hack4impact-uiuc/mentee pull request #154
Opened 2021-01-02 20:49 UTC by AzureQDragon

## Status:
:rocket: Ready

## Description :star2:

Fixes #140 
 
## TODOs :star:

2021-01-02 20:59 UTC, AngelaLuo49021 approved these changes
Good stuff

2021-01-04 15:45 UTC, chyku requested changes
looks fine but some cleanup needed, also we're gonna need to add these fields to the database before this code is pushed to master

2021-01-04 15:45 UTC, chyku commented on backend/api/views/appointment.py
> +        print(data.get("allow_calls"))
delete print lol

2021-01-04 15:45 UTC, chyku commented on backend/api/views/appointment.py
> +        print(e)
is this needed here still? generally when theres an exception u wanna create a response with error code + message but idk if u left this while debugging something

2021-01-04 16:53 UTC, chyku approved these changes

2021-01-04 16:59 UTC, merged