Fix mentee book appointment
hack4impact-uiuc/mentee pull request #156
Opened 2021-01-02 21:51 UTC by AzureQDragon

## Status:

## Description :star2:

Fixes #number
 
## TODOs :star:

2021-01-06 21:32 UTC, AngelaLuo49021 requested changes
Bug: all available appointment times show up as 00:00 - 00:00

2021-01-06 22:38 UTC, AzureQDragon commented
> Bug: all available appointment times show up as 00:00 - 00:00

I think that's not a bug but rather a product of the fact that jim watson happens to have all of his appointments at 00:00 - 00:00 since it's currently shown in 24hr time.

2021-01-07 01:45 UTC, AngelaLuo49021 reviewed
It still does 00:00 for my times. 
![image](https://user-images.githubusercontent.com/42478474/103840605-82b1cf80-5057-11eb-815a-4584dd3350b3.png)
![image](https://user-images.githubusercontent.com/42478474/103840683-a248f800-5057-11eb-89e8-3780b30a741a.png)
![image](https://user-images.githubusercontent.com/42478474/103840721-bb51a900-5057-11eb-90ab-8c9be5deec0b.png)

2021-01-09 19:31 UTC, chyku requested changes
not a full review, just noticed a few things & pls add documentation for unclear code!

2021-01-09 19:31 UTC, chyku commented on frontend/src/components/MenteeAppointmentModal.js
>    const [appModalVisible2, setAppModalVisible2] = useState(false);
this is kind of weird naming for a state, what does this mean & why are there 2 of them?

2021-01-09 19:32 UTC, AngelaLuo49021 commented on frontend/src/components/MenteeAppointmentModal.js
>    const [appModalVisible2, setAppModalVisible2] = useState(false);
@Lam7150

2021-01-09 19:47 UTC, AngelaLuo49021 requested changes
Some of the CSS on the form got messed up 
Before:
![image](https://user-images.githubusercontent.com/42478474/104107316-d5ba9b00-5280-11eb-92b7-2785eaf2e55a.png)
After:
![image](https://user-images.githubusercontent.com/42478474/104107331-eb2fc500-5280-11eb-9383-68edfa722a18.png)

Make the bubbles bigger to fit in the time (time is preferably centered too):
![image](https://user-images.githubusercontent.com/42478474/104107365-2500cb80-5281-11eb-82ff-0ab9d7c2f045.png)

(highly appreciated but not high pri)
Also could the times not be in military times? include am/pm

2021-01-14 18:29 UTC, Lam7150 commented on frontend/src/components/MenteeAppointmentModal.js
>    const [appModalVisible2, setAppModalVisible2] = useState(false);
just saw this oops github didn't send me a notification, but that's the state to open/close the modal's in sequential order (although the naming is weird), I would recommend changing it if you find a better solution though as that was done a bit hastily to meet deadlines

2021-01-14 20:41 UTC, AngelaLuo49021 approved these changes
Beautiful

2021-01-14 20:57 UTC, chyku requested changes
mostly nits but smol things, overall looks aight pls try to avoid sus code & mark todos where u think its sus lol

2021-01-14 20:57 UTC, chyku commented on frontend/src/components/MenteeAppointmentModal.js
>    const [appModalVisible2, setAppModalVisible2] = useState(false);
yea would prefer this changed to mentioning which modal & not a general appmodal

2021-01-14 20:57 UTC, chyku commented on frontend/src/components/MenteeAppointmentModal.js
> +  const [numInputs] = useState(11);
if numinputs doesn't change you can make this const numinputs = 11

2021-01-14 20:57 UTC, chyku commented on frontend/src/components/MenteeAppointmentModal.js
> +  // Move on to next page if time is truthy
IMO the "if time is truthy" part isn't necessary as the code `if (time)` says it for you, but it would be helpful if you could move this to line 132 and describe that what's happening w all the setAppModalVisibles is that you're moving onto the next page

2021-01-14 20:57 UTC, chyku commented on frontend/src/components/MenteeAppointmentModal.js
> +    // POST request to create mentee appointment
also not super necessary comment- if your code says what it's doing, no need to comment

2021-01-14 20:57 UTC, chyku commented on frontend/src/components/MenteeAppointmentModal.js
> +                Mentoring Session with Bernie Sanders
can you put a todo here or fill in mentor name if it's easy to

2021-01-14 20:57 UTC, chyku commented on frontend/src/components/css/Modal.scss
> +    border-color: inherit !important;
yea what is going on here lol

2021-01-14 20:57 UTC, chyku commented on frontend/src/utils/consts.js
> +export const KEYS = [
can u make the constant name specific to your form (i.e. appointment form keys)

2021-01-14 23:18 UTC, AzureQDragon commented on frontend/src/components/css/Modal.scss
> +    border-color: inherit !important;
So in order to override ant design changes I had to use !important, but I don't know if there is a better way to do this

2021-01-18 19:05 UTC, chyku approved these changes
we do love to see it!! also if there are no issues listed for the todos in here (replacing bernie sanders, timezone), pls write some up

2021-01-19 17:59 UTC, merged