Notifications settings backend
hack4impact-uiuc/mentee pull request #158
Opened 2021-01-07 04:19 UTC by Leundai

## Status: :rocket: Ready

## Description :star2:

Fixes #155
 * Added fields to `MentorProfile.py`
 * Added fields support for editing and creating mentor profile endpoints
 * Restricted email notifications if email field is false 
 * 
## TODOs :star:
- [ ] Tests
- [X] Documentation

2021-01-07 04:21 UTC, Leundai commented on backend/api/views/appointment.py
> -        return create_response(status=503, message=msg)
I decided on deleting this since I don't think failing the endpoint will be necessary. Otherwise, we will lose that created appointment.

2021-01-09 19:29 UTC, chyku requested changes

2021-01-09 19:29 UTC, chyku commented on backend/api/views/main.py
> +        email_notifications=date["email_notifications"],
date or data

2021-01-09 19:29 UTC, chyku commented on backend/api/views/main.py
> +        text_notifications=data["text_notifications"],
@AngelaLuo49021 should we default these to true on profile creation

2021-01-09 19:29 UTC, AngelaLuo49021 commented on backend/api/views/main.py
> +        text_notifications=data["text_notifications"],
yeah lets do that

2021-01-09 20:35 UTC, chyku requested changes

2021-01-09 20:35 UTC, chyku commented on backend/api/views/main.py
> +        text_notifications=data.get("text_notifications", False),
if this is going to be default true, just set these to true here instead of getting from data (probably won't be in there if it's always true)

2021-01-09 21:10 UTC, Leundai commented on backend/api/views/main.py
> +        text_notifications=data.get("text_notifications", False),
mb completely misread it thinking the default was false not true

2021-01-10 21:06 UTC, chyku approved these changes
:+1: :100:

2021-01-11 20:02 UTC, AngelaLuo49021 approved these changes
good stuff

2021-01-13 23:22 UTC, merged