Small bugfixes
hack4impact-uiuc/mentee pull request #168
Opened 2021-01-14 19:41 UTC by chyku

## Status: :construction: In development

## Description :star2:

Fixes:
- mentor gallery links work now
- remove settings tab
- remove notif bell
- updated home text

2021-01-14 20:10 UTC, AngelaLuo49021 requested changes
Also on the mentor's profiles both in the portal and on the page, you can't click the link to access it. 
![image](https://user-images.githubusercontent.com/42478474/104643600-417e7880-5672-11eb-990a-94fff298e26a.png)

2021-01-14 20:10 UTC, AngelaLuo49021 commented on frontend/src/components/MentorCard.js
> +              href={"//" + props.website}
i think you need "://"

2021-01-14 20:10 UTC, AngelaLuo49021 commented on frontend/src/components/MentorCard.js
> +              href={"//" + props.linkedin}
same here, it dont work when i tested it

2021-01-14 20:29 UTC, chyku commented on frontend/src/components/MentorCard.js
> +              href={"//" + props.website}
this worked tho lol

2021-01-14 20:29 UTC, chyku commented on frontend/src/components/MentorCard.js
> +              href={"//" + props.linkedin}
oh wtf

2021-01-14 22:10 UTC, Leundai approved these changes
lgtm!

2021-01-15 05:53 UTC, AngelaLuo49021 approved these changes
Looks good!

2021-01-18 19:39 UTC, merged