POST Mentor Profile
hack4impact-uiuc/mentee pull request #17
Opened 2020-10-06 20:54 UTC by Leundai

## Status: :construction:

## Description :star2:

Fixes #5 
Defines the format of the post request data which can be used throughout the other kinds of queries.
### **Important**
Let's remain consistent with the naming of our data body as well. So lmk if there are any changes to be added to this PR.

## TODOs :star:

2020-10-08 22:05 UTC, chyku commented on backend/api/utils/request_utils.py
> +    # TODO: Possibly include WTForms instead in order to simplify this type of checking
+1! was looking at https://pythonhosted.org/Flask-Inputs/ for a flask-specific library for input validation

2020-10-15 22:42 UTC, chyku requested changes
mostly code style nitpiks

2020-10-15 22:42 UTC, chyku commented on backend/api/views/main.py
> +        # Runs through every video and validates it if it is fully filled then add to database
also not entirely necessary comment- my philosophy on comments has always been to explain not obvious code or complex logic or strange bugfixes etc, but i think this is fairly straightforward

2020-10-15 22:42 UTC, chyku commented on backend/api/views/main.py
> +        for i, video in enumerate(videos_data):
if you're just using `i` to specify exactly which video is missing something, it's not necessary- that's kind of a lot of extra detail to put into an error message for something that might not happen esp if we validate on frontend

2020-10-15 22:42 UTC, chyku commented on backend/api/utils/request_utils.py
> +# Also patches WTForms with supporting code for JSON
no need for this lvl of detail on line 9 lol

2020-10-15 22:42 UTC, chyku commented on backend/api/views/main.py
> +    # If option field Biography is passed
all these "if optional field.. is passed" comments are relatively unnecessary

2020-10-15 22:42 UTC, chyku commented on backend/api/views/main.py
> +        new_mentor.biography = data["biography"]
instead of doing checks like this you can do something similar to @AzureQDragon where you set it to None if it doesn't exist- OR even better, you can pass data.get(biography) into the constructor to extra clean your code
```suggestion
new_mentor.biography = data.get("biography")
```
since dict.get defaults to None if nothing's there

2020-10-15 23:08 UTC, chyku approved these changes
beautiful

2020-10-19 21:47 UTC, AngelaLuo49021 approved these changes
looks gucci

2020-10-19 22:36 UTC, merged