PUT mentor profile
hack4impact-uiuc/mentee pull request #18
Opened 2020-10-06 21:06 UTC by AzureQDragon

## Status:
:construction: In development

## Description :star2:
Adding PUT request for mentor profiles and defining parameters.
Fixes #6 
 
## TODOs :star:
- [ ] Add request
- [ ] Documentation
- [ ] Review

2020-10-13 20:45 UTC, chyku commented
uhh wait how did you change the "majors" field in education if there isn't supposed to be one lol

2020-10-14 20:34 UTC, Leundai commented on backend/api/views/main.py
> +            tag=video_data.get("tag"),
@chyku I might have missed out on this detail but are we keeping video in the mentor profile data model? @AzureQDragon I like the code though! Good stuff. I'm wondering if we are doing multiple videos since ik Kelley mentioned that it would be a list of videos. So would PUT only update a single video or multiple.

2020-10-14 20:34 UTC, Leundai commented on backend/api/views/main.py
> +    mentor.name = data.get("name", mentor.name)
TIL there is a dict.get( ) that allows for two params for the default value. Good stuff.

2020-10-14 20:39 UTC, AzureQDragon commented on backend/api/views/main.py
> +            tag=video_data.get("tag"),
I think we decided to keep it for now, but we might remove it later.

2020-10-15 17:03 UTC, chyku requested changes
video -> videos, can shorten error checking

2020-10-15 17:03 UTC, chyku commented on backend/api/views/main.py
> +        return create_response(status=400, message=msg)
not sure if this case will ever happen- if the body is empty request.get_json fails. it's also worth noting that this case _probably_ won't happen as i'd hope whoever makes requests from the frontend knows that post requests need data, so there's less need to check for this

2020-10-15 17:03 UTC, chyku commented on backend/api/views/main.py
> +            tag=video_data.get("tag"),
pls refactor as if it's a list of videos, not just one

2020-10-15 22:49 UTC, chyku approved these changes
we luv 2 see it

2020-10-15 23:13 UTC, Leundai approved these changes

2020-10-15 23:17 UTC, merged