Admin mentor endpoints
hack4impact-uiuc/mentee pull request #194
Opened 2021-02-09 00:36 UTC by nroy20

## Status: 🚧 

## Description :star2:
Creating backend endpoints for admin mentor. Allows admin to delete mentors and upload a file that creates whitelisted emails.
Fixes #191 
 
## TODOs :star:

2021-02-26 01:05 UTC, AngelaLuo49021 requested changes

2021-02-26 01:05 UTC, AngelaLuo49021 commented on backend/api/views/admin.py
> +def upload_emails():
![image](https://user-images.githubusercontent.com/42478474/109239920-107a8300-779c-11eb-8f73-982a565b4422.png)
We want a separate verified email object for each email. For mentors you can just make the password an empty string.

2021-02-26 01:05 UTC, AngelaLuo49021 commented on backend/api/views/admin.py
> +        mentor = MentorProfile.objects.get(id=mentor_id)
We need to delete the users object too or else they will still be able to login 
![image](https://user-images.githubusercontent.com/42478474/109240004-3d2e9a80-779c-11eb-86b4-60c6d3e09b64.png)
Mentor Profile user_id = User _id

2021-03-04 16:52 UTC, AngelaLuo49021 requested changes
One smol change, but everything else looks good! Can you update the postman pictures in your PR too?

2021-03-04 16:52 UTC, AngelaLuo49021 commented on backend/api/views/admin.py
> +        uploads = AdminEmails.objects().get(is_mentor=False)
I think you should be using the VerifiedEmail model not the AdminEmail model for both of these endpoints. This is what the database looks like 
![image](https://user-images.githubusercontent.com/42478474/109998995-663cb700-7cd7-11eb-8417-9c33d461a4cb.png)
set the mentor password field to an empty string for consistency

2021-03-04 17:14 UTC, kenetec requested changes
Great job! 🤩 I think you just need to switch stuff from `AdminEmails` to `VerifiedEmail` and then you're good!

2021-03-04 17:14 UTC, kenetec commented on backend/api/models/__init__.py
> +from .AdminEmails import AdminEmails
I think we're using `VerifiedEmail` instead of `AdminEmails` so if you could change that in `admin.py` too, then your PR will be :fire:

2021-03-09 00:35 UTC, AngelaLuo49021 approved these changes
Very Cool

2021-03-09 01:26 UTC, kenetec approved these changes
beautifulll 😝

2021-03-09 01:52 UTC, merged