Add navbars to appointments page
hack4impact-uiuc/mentee pull request #20
Opened 2020-10-06 21:36 UTC by Feeshay

## Status:

## Description :star2:

Fixes #number
 
## TODOs :star:

2020-10-14 02:48 UTC, AngelaLuo49021 requested changes

2020-10-14 02:48 UTC, AngelaLuo49021 commented on frontend/src/components/App/App.js
> +        <Route path="/" exact component={Home} />
So what we want is for the navbar to stay there when we switch between appointments, videos, etc. 

First Approach
-What you can do is change the <Appointments> Component to <Navbar> and surround the <Route>s. Then create a separate appointments page. [stackoverflow reference](https://stackoverflow.com/questions/45781056/react-router-dom-how-to-include-a-navigation-bar-on-every-page)
- For every page in the Mentor portal we create, we would need to load in a Navbar so you would need to change it to not be customized to appointments. Everytime a mentor switches tabs, the entire navbar and page would reload

Second Approach (Better, what we want)
- Another approach is you could put the <HomePage>, <Videos>, etc components inside <Content> of the navbar and have the corresponding one render when pressing the right button
- Instead of naming the componenet, "Appointments", name it "MentorPortal" as it serves as the base for the entire portal 
- This would remove the page routes you already made for the other pages and simply make them components inside the navbar (Having the router set up is awesome though for future work!)

2020-10-14 02:48 UTC, AngelaLuo49021 commented on frontend/src/components/pages/Appointments.js
> +                {displayDropdown ? <CaretUpOutlined /> : <CaretDownOutlined />}
Could you add the dropdown boxes now that faith has the designs up? 
![image](https://user-images.githubusercontent.com/42478474/95935832-cb7c2400-0d99-11eb-9f87-07119e5fb118.png)

2020-10-15 23:05 UTC, chyku approved these changes
ur a god

2020-10-15 23:05 UTC, chyku commented on frontend/src/components/App/App.js
> +    <>
not necessary to have this since Router is the parent element right

2020-10-15 23:05 UTC, chyku commented on frontend/src/components/App/App.js
> +          component={() => <Navigation content={<Home />} page="home" />}
does component have to be formatted as a function?

2020-10-15 23:14 UTC, Feeshay commented on frontend/src/components/App/App.js
> +          component={() => <Navigation content={<Home />} page="home" />}
So we need to pass in an object of some sort if we use `component=` but we could also use render. I think the main detriment to using a function is that the component has to mount/unmount but idk if that's too much of an issue since we have basically a static prop and aren't routing too often

https://ui.dev/react-router-v4-pass-props-to-components/

2020-10-15 23:18 UTC, AngelaLuo49021 commented
small changes, extend content to the bottom of the page, right now it stops like 7/8 way through
Also top left drop down needs to move to the right a bit.
Overall very cool! thanks Michael 👍

2020-10-15 23:18 UTC, AngelaLuo49021 approved these changes

2020-10-16 00:48 UTC, merged