Download endpoints
hack4impact-uiuc/mentee pull request #204
Opened 2021-02-19 00:39 UTC by chenfeiyu132

## Status: :rocket:

## Description :star2:

Implements #192. Created new view "download" with two endpoints(`/accounts/all`and `/appointments/all`) which are responsible for converting the Mongo documents for mentor_profiles and appointments, respectively, into excel files and sending them to the user.
 
## TODOs :star:

2021-02-21 02:27 UTC, Leundai requested changes

2021-02-21 02:27 UTC, Leundai commented on backend/api/views/appointment.py
> +
The wait would this be needed at all if there already exists a function like this in `downloads.py`?

2021-02-21 02:27 UTC, Leundai commented on backend/api/views/download.py
> +    return send_file(output, attachment_filename="accounts.xlsx", as_attachment=True)
a try/catch might be useful here just to follow the same pattern as lines 37-42

2021-02-21 06:56 UTC, chenfeiyu132 commented on backend/api/views/appointment.py
> +
Ooops originally wrote it in appointments.py forgot to delete

2021-02-21 06:56 UTC, chenfeiyu132 commented on backend/api/views/download.py
> +    return send_file(output, attachment_filename="accounts.xlsx", as_attachment=True)
Say less

2021-02-21 22:58 UTC, Leundai approved these changes
lgtm! Just make sure to `yarn format` on the root folder project. @kenetec @AngelaLuo49021 
do you guys think it would be okay to have the boolean columns like `allow phone calls` stay as 0/1 instead of T/F?

2021-02-22 17:48 UTC, AngelaLuo49021 requested changes
One small thing, everything else looks good!

2021-02-22 17:48 UTC, AngelaLuo49021 commented on backend/api/views/download.py
> +    df = pd.DataFrame(accts, columns=["mentor name", "location", "email", "phone_number", "professional_title", "linkedin", "website", "image url", "educations", "languages", "specializations", "biog
add a boolean field for whether they have a video up or not

2021-02-22 17:49 UTC, AngelaLuo49021 commented on backend/api/views/download.py
> +    df = pd.DataFrame(accts, columns=["mentor name", "location", "email", "phone_number", "professional_title", "linkedin", "website", "image url", "educations", "languages", "specializations", "biog
and yes what Leo said about making boolean fields T/F instead of 0/1

2021-02-22 22:43 UTC, kenetec approved these changes
Looks good 😍! There is a bit of repetitive code so consolidate that before you merge

2021-02-22 22:43 UTC, kenetec commented on backend/api/views/download.py
> +    output = BytesIO()
Can you move this into a function that takes in the `sheet_name` and either `appts/accts.`

2021-02-22 22:44 UTC, kenetec commented on backend/api/views/download.py
> +    output.seek(0)
Can you move this into a function that takes in the `sheet_name` and either `appts/accts.`

2021-02-23 01:01 UTC, AngelaLuo49021 approved these changes
Looks good!

2021-03-02 02:07 UTC, merged