Mentee model
hack4impact-uiuc/mentee pull request #209
Opened 2021-02-24 17:46 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #number
 
## TODOs :star:

2021-02-24 19:01 UTC, Leundai commented on backend/api/views/main.py
> +@main.route("/account/<id>/image", methods=["PUT"])
This is the type of refactoring I'm thinking of doing for the next PR regarding endpoints and adjusting the API wrapper endpoints in the frontend

2021-02-26 00:44 UTC, AngelaLuo49021 requested changes
Looks good, some fields need to be adjusted

2021-02-26 00:44 UTC, AngelaLuo49021 commented on backend/api/models/MenteeProfile.py
> +    age = IntField(required=True)
Make it a string 
![image](https://user-images.githubusercontent.com/42478474/109238313-effcf980-7798-11eb-97d5-2c5cfad4211b.png)

2021-02-26 00:44 UTC, AngelaLuo49021 commented on backend/api/models/MenteeProfile.py
> +    specialist_categories = ListField(StringField(), required=True)
remove this. We need them to enter this in for each appointment they make because each appointment may have a different category they want to focus on

2021-02-26 00:44 UTC, AngelaLuo49021 commented on backend/api/models/MenteeProfile.py
> +    linkedin = StringField()
remove

2021-02-26 00:44 UTC, AngelaLuo49021 commented on backend/api/models/MenteeProfile.py
> +    website = StringField()
remove

2021-03-01 23:28 UTC, AngelaLuo49021 approved these changes
Looks good to me now!

2021-03-02 00:44 UTC, kenetec approved these changes
cool 🅱eans

2021-03-02 00:44 UTC, kenetec commented on frontend/src/utils/api.js
> +export const uploadMentorImage = (data, id, type) => {
I think we can refactor this to be `uploadAccountImage` or something or more general, and then create an `uploadMentorImage` function that calls this function with `mentor` as the `type`. This way, we can avoid having to change a bunch of all files if we decide to change the values of `type` later on

2021-03-02 00:44 UTC, kenetec commented on backend/api/views/main.py
> +@main.route("/account/<id>/image", methods=["PUT"])
Sounds good!

2021-03-02 00:44 UTC, kenetec commented on frontend/src/utils/api.js
> +  const requestExtension = "/account/" + id + "/image";
Try using the [string interpolation syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) for this.

2021-03-03 06:29 UTC, merged