Mentor application
hack4impact-uiuc/mentee pull request #212
Opened 2021-02-26 20:36 UTC by IshaanRSharma

## Status:

## Description :star2:

Fixes #202 
 
## TODOs :star:

2021-03-05 00:46 UTC, AngelaLuo49021 requested changes
A few field adjustments

2021-03-05 00:46 UTC, AngelaLuo49021 commented on backend/api/models/MentorApplication.py
> +    buisness_number = StringField()
we love the spelling

2021-03-05 00:46 UTC, AngelaLuo49021 commented on backend/api/models/MentorApplication.py
> +    verified = BooleanField(required=True)
in the designs we have the app in different state [pending, reviewed, rejected, offer made, rejected]. A verified boolean is probably not the best way to represent this

2021-03-05 00:46 UTC, AngelaLuo49021 commented on backend/api/models/MentorApplication.py
> +
Also have a date submitted field

2021-03-05 00:54 UTC, kenetec approved these changes
sweeet 😎 Wait to merge #216  before merging this one.

2021-03-09 00:45 UTC, AngelaLuo49021 requested changes

2021-03-09 00:45 UTC, AngelaLuo49021 commented on backend/api/models/MentorApplication.py
> +    guidance_topics = ListField(StringField(), required=True)
Can you change guidance_topics to "specializations" for consistency with our mentor profiles?

2021-03-09 00:45 UTC, AngelaLuo49021 commented on backend/api/views/apply.py
> +
Add one more endpoint
Get all application's application id, mentor name, mentor speacializations

2021-03-09 01:17 UTC, AngelaLuo49021 requested changes

2021-03-09 01:17 UTC, AngelaLuo49021 commented on backend/api/models/MentorApplication.py
> +    verified = StringField(required=True)
application_state

2021-03-10 21:14 UTC, Leundai commented on backend/api/models/MentorApplication.py
> +    notes = StringField()
@AngelaLuo49021 @kenetec Should this be a list of notes? Instead of a single string. Also for the design, there is no garbage can so that one can't delete a note if it is made by mistake.
![image](https://user-images.githubusercontent.com/28935000/110698469-50d1fc00-81b3-11eb-99af-2d3cb3089010.png)

2021-03-11 02:34 UTC, kenetec commented on backend/api/models/MentorApplication.py
> +    notes = StringField()
Ya I think we're gonna move forward with keeping it as a string field for now, and then come back later to change it to a list of strings. But @AngelaLuo49021 should confirm that as well

2021-03-12 00:42 UTC, AngelaLuo49021 approved these changes
Looks good!

2021-03-12 22:57 UTC, merged