💂‍♀️ Admin Account Data Page
hack4impact-uiuc/mentee pull request #217
Opened 2021-03-04 07:43 UTC by Leundai

## Status:

## Description :star2:

Fixes #number
 
## TODOs :star:

2021-03-04 17:12 UTC, AngelaLuo49021 requested changes
small change request, will do full review soon tho

2021-03-04 17:12 UTC, AngelaLuo49021 commented on frontend/src/components/pages/AdminAccountData.js
> +                href={formatLinkForHref(`localhost:3000/gallery/${id}`)}
maybe we can have a prod env variable to toggle between the real url and localhost so its not hardcoded in?

2021-03-05 01:07 UTC, kenetec approved these changes
gravy 👶🏿

2021-03-05 01:07 UTC, kenetec commented on frontend/src/components/css/AdminAccountData.scss
> +    width: 216px;
Try using `em` here

2021-03-05 01:13 UTC, kenetec commented on frontend/src/components/pages/AdminAccountData.js
> +                href={formatLinkForHref(`localhost:3000/gallery/${id}`)}
Note: for frontend, you have to prefix env variables with `REACT_APP_`

2021-03-12 00:53 UTC, AngelaLuo49021 approved these changes
This isn't completely connected to backend (downloading data doesnt work) but we can circle back to that in a new issue. Good stuff leo!!!!

2021-03-12 00:56 UTC, merged