Mentor mob compatibility
hack4impact-uiuc/mentee pull request #220
Opened 2021-03-05 00:31 UTC by chenfeiyu132

## Status:
:rocket: Ready

## Description :star2:

Fixes #205 by making couple of changes to the CSS on the mentor side. Made the sidebar collapsible. Made login page mobile compatible by removing the MENTEE icon if the screen gets too small. Changed the formatting of the mentor profile page so that the contact info on the side can be shifted to the bottom in mobile view. Navbar logo changes with css by switching between icons based on screen size.
 
## TODOs :star:

2021-03-08 18:38 UTC, kenetec approved these changes
amazing work!! 🤩 i left a few suggestions

2021-03-08 18:38 UTC, kenetec commented on frontend/src/components/MentorNavHeader.js
> +  const isMobile = useMediaQuery({ query: `(max-width: 500px)` });
This is used a few times in the codebase, I think it would make more sense to wrap this `useMediaQuery()` fn into an `isMobile()` fn that calls either `500px` or `768px` and then just import that function where you need it.

2021-03-08 18:38 UTC, kenetec commented on frontend/src/components/css/MentorModal.scss
> +    font-size: 3vh;
Maybe use `em` here? I think the text might look weird on screens with more height.

2021-03-09 00:33 UTC, AngelaLuo49021 approved these changes
Very pretty

2021-03-09 01:28 UTC, AngelaLuo49021 requested changes
![image](https://user-images.githubusercontent.com/42478474/110404439-78568680-8044-11eb-801a-274dce65f6d4.png)
Small thing, but its collapsing on full screen too so maybe change the limit of when it collapses

2021-03-09 01:29 UTC, AngelaLuo49021 reviewed
For the last change I requested, if its not a quick fix then just move onto an MVP feature and we can merge this in post MVP

2021-03-09 01:38 UTC, AngelaLuo49021 reviewed
![image](https://user-images.githubusercontent.com/42478474/110405216-dcc61580-8045-11eb-9bd0-b2d988f8b9f4.png)
why is the logo so fat lmao, can u put it back to small

2021-03-12 00:59 UTC, AngelaLuo49021 approved these changes
Looks good!

2021-03-12 01:31 UTC, merged