Mentee account refactor
hack4impact-uiuc/mentee pull request #222
Opened 2021-03-05 13:37 UTC by Leundai

## Status:

## Description :star2:

Fixes #number
 
## TODOs :star:

2021-03-12 01:44 UTC, kenetec requested changes
awesome stufff!! I think you just need to move some stuff around and then your PR is golden

2021-03-12 01:44 UTC, kenetec commented on frontend/src/utils/api.js
> +  const requestExtension = `/account/${id}/image`;
using string interpolation * chef's kiss *

2021-03-12 01:44 UTC, kenetec commented on frontend/src/utils/apiHelper.js
> +import {
Might be a little weird to have two files for api. I recommend adding all the functions to `api.js` and adding comments to delineate sections (as long as there's no name conflicts).

2021-03-16 00:33 UTC, kenetec approved these changes
awesome work 🤩

2021-03-16 21:16 UTC, AngelaLuo49021 approved these changes
Love it

2021-03-16 21:31 UTC, merged