All Appointments Data Page
hack4impact-uiuc/mentee pull request #236
Opened 2021-03-16 01:07 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #214 
 
## TODOs :star:
- [ ] Tests
- [ ] Documentation

2021-03-19 23:48 UTC, Leundai commented on backend/api/views/appointment.py
> +def get_appointments():
This is really slow 💀takes about 5-6 seconds to load up. Not too sure what might help with this

2021-03-20 16:57 UTC, kenetec approved these changes
Great job!! 🔥 If you wanna play around with the suggestions I made, feel free to -- otherwise you can just create an issue for the slow endpoint

2021-03-20 16:57 UTC, kenetec commented on backend/api/views/appointment.py
> +def get_appointments():
Could we try paginating (or infinite scroll with a load when we reach the bottom) on the client side and then requesting a range of appointments.

2021-03-20 16:57 UTC, kenetec commented on backend/api/views/appointment.py
> +    appointments = AppointmentRequest.objects()
Also maybe we can query the fields we only need from appointments.

2021-03-20 16:57 UTC, kenetec commented on frontend/src/components/AdminDropdowns.js
> +  );
Could we make this scrollable? It's pretty big at the moment

2021-03-20 16:57 UTC, kenetec commented on frontend/src/components/pages/AdminAppointmentData.js
> +      <Spin spinning={isLoading} size="large" style={{ height: "100vh" }}>
*chef's kiss*

2021-03-20 16:57 UTC, kenetec commented on frontend/src/components/pages/AdminAppointmentData.js
> +            {filterData.map((data, i) => {
You can remove `i` from the parameters if you aren't using it

2021-03-20 16:57 UTC, kenetec commented on frontend/src/components/pages/AdminAppointmentData.js
> +    setFiltering(!filtering);
I'd explictly set these to `false` or `true` just in case the variables somehow get out of sync in some edge case

2021-03-20 21:07 UTC, Leundai commented on backend/api/views/appointment.py
> +    appointments = AppointmentRequest.objects()
created an issue for it! :)

2021-03-20 22:57 UTC, AngelaLuo49021 requested changes
Absolutely beautiful Leonardo. Just one small thingy. The cursor on the cards is right now a pointer but we want it to be a hand to indicate that it is clickable so in the CSS we want cursor: grab;

2021-03-21 00:22 UTC, AngelaLuo49021 approved these changes
Beautiful

2021-03-21 00:55 UTC, merged