Admin Account Data - Delete Account
hack4impact-uiuc/mentee pull request #237
Opened 2021-03-16 01:16 UTC by Leundai

## Status: :rocket: Ready

## Description :star2:

Fixes #number
 
## TODOs :star:

2021-03-16 21:06 UTC, AngelaLuo49021 reviewed
@kenetec regarding leo's note about the endpoint failing if there is no verification email do we want to adjust that endpoint?

2021-03-16 21:06 UTC, AngelaLuo49021 approved these changes
Looks good! may have to refactor backend as seen in my previous comment

2021-03-16 21:14 UTC, AngelaLuo49021 requested changes
Could you add a verification modal before the account deletes? It should be super simple "Are you sure you want to delete "Angela Luo" No, Yes

2021-03-18 01:23 UTC, AngelaLuo49021 approved these changes
Looks great!

2021-03-18 18:01 UTC, kenetec commented
> @kenetec regarding leo's note about the endpoint failing if there is no verification email do we want to adjust that endpoint?

ya i think that's a good idea

2021-03-18 18:39 UTC, kenetec approved these changes
awesome job! 😛

2021-03-18 18:39 UTC, kenetec commented on backend/api/views/download.py
>              attachment_filename="{0}.xlsx".format(sheet_name),
Can we use `f'abc'` here?

2021-03-18 18:39 UTC, kenetec commented on frontend/src/utils/api.js
> +        console.log(response);
delete `console.log`

2021-03-18 23:41 UTC, merged