Adding availability model
hack4impact-uiuc/mentee pull request #25
Opened 2020-10-13 20:21 UTC by Lam7150

## Status: :rocket: Ready

## Description :star2:
Availability will be represented as a list of objects with { startTime, endTime }, with querying explained here: https://stackoverflow.com/questions/42068483/mongodb-between-date-range-query-nested-property 

This should comply with Mongo's document schema, while allowing us to query efficiently.

Fixes #16 
 
## TODOs :star:

2020-10-13 20:43 UTC, chyku requested changes
small things

2020-10-13 20:43 UTC, chyku commented on backend/api/models/Availability.py
> +                    end_time: {self.end_time}>"""
please include name of model here

2020-10-13 20:43 UTC, chyku commented on backend/api/models/__init__.py
>  __all__ = ["db", "Email", "Person", "Education", "Video", "MentorProfile"]
also have to add Availability in this array lol

2020-10-16 15:12 UTC, chyku requested changes
ONE TINY THING otherwise it's good

2020-10-16 15:12 UTC, chyku commented on backend/api/models/__init__.py
> +from .Availability import Availability
WAIT SORRY im p sure you have to import this before mentorprofile or else mentorprofile will throw a fit because it depends on availability

2020-10-16 18:04 UTC, Lam7150 commented on backend/api/models/__init__.py
> +from .Availability import Availability
fixed!

2020-10-17 00:13 UTC, Leundai approved these changes

2020-10-17 00:14 UTC, Leundai approved these changes
Good stuff

2020-10-18 20:57 UTC, AngelaLuo49021 approved these changes
looks good!

2020-10-18 21:00 UTC, chyku approved these changes
lgtm

2020-10-19 21:53 UTC, merged