admin sign in frontend
hack4impact-uiuc/mentee pull request #250
Opened 2021-03-22 23:59 UTC by IshaanRSharma

## Status:
:construction: In development

## Description :star2:
<img width="1435" alt="sign in admin " src="https://user-images.githubusercontent.com/44181424/112072828-e9f7ff80-8b2f-11eb-883d-6034b56623fc.png">

A sign-in page for admins.
Fixes #239 
 
## TODOs :star:
Auth connection.

2021-03-26 00:21 UTC, AngelaLuo49021 requested changes
can you pull from dev so you get the updated navbar at the top your branch v out of date

2021-03-26 00:58 UTC, AngelaLuo49021 approved these changes
Look good

2021-03-26 00:59 UTC, kenetec requested changes
looks gucci, just a quick change and ur good to go

2021-03-26 00:59 UTC, kenetec commented on package.json
> +        "react-dropzone": "^11.3.1"
can you add these to the frontend's package json instead

2021-03-27 15:59 UTC, kenetec approved these changes
sweeet 😎

2021-03-27 18:27 UTC, merged