Mentor Profile Modal Fix
hack4impact-uiuc/mentee pull request #251
Opened 2021-03-25 21:31 UTC by Leundai

## Status: :rocket: Ready

## Description :star2:

Fixes #221 

- Improved mobile compatibility of profile editing modal
- removed duplication of the profile page (page element was rendering twice)

## Screenshots
![image](https://user-images.githubusercontent.com/28935000/112546456-72241200-8d87-11eb-82f7-ea4d4cf8162c.png)

## TODOs :star:
- [X] Tests
- [X] Documentation

2021-03-25 23:34 UTC, AngelaLuo49021 requested changes
Looks good but now the navbar on the side is always collapsed for me?

https://user-images.githubusercontent.com/42478474/112556685-b4a21a80-8d98-11eb-8ec6-23eb21a8c936.mov

2021-03-30 00:35 UTC, kenetec approved these changes
Looks beautiful! Make sure to delete `MainNavHeader.js`, we won't need that

2021-03-30 00:35 UTC, kenetec commented on frontend/src/components/MainNavHeader.js
> +import { Layout } from "antd";
You can delete this file

2021-04-05 23:55 UTC, AngelaLuo49021 approved these changes
Looks great now! <3

2021-04-05 23:57 UTC, merged