Message endpoints
hack4impact-uiuc/mentee pull request #270
Opened 2021-03-30 00:38 UTC by chenfeiyu132

## Status:

:rocket: Ready

## Description :star2:

Fixes #219. Added message model in backend along with endpoints GET:all messages, messages based on user_id/user_name/message_id,PUT:update any field of message,POST:create new message,DELETE:delete based on message_id
 
## TODOs :star:

2021-04-01 21:55 UTC, kenetec requested changes
Good stuff! There's some changes you'll need to make regarding the composition of endpoints but lemme know if you have any questions about the comments I left!

2021-04-01 21:55 UTC, kenetec commented on backend/api/models/Message.py
> +    time = DateTimeField(reqruied=True)
`required` is misspelled here

2021-04-01 21:55 UTC, kenetec commented on backend/api/views/messages.py
> +    return create_response(data={"Messages": messages}, status=200, message="Success")
So we can actually pass params into the GET request that can directly correspond with the fields we want to query by. The url would pretty much look something like `/api/messages/?from_id=a23b64c&to_id=db324m`, and you'll be able to access these values with `request.args`. Try removing these endpoints and use the endpoint for getting all endpoints to query messages based on any field.

2021-04-01 21:55 UTC, kenetec commented on backend/api/views/messages.py
> +        return create_response(status=422, message=msg)
We don't need to have `/<field:value>`, we can actually grab as many fields as we want from the request body (`request.json`).

2021-04-01 21:55 UTC, kenetec commented on backend/api/views/messages.py
> +    )
I think this should go in the `try` block, it might error if there's a `None` value when creating.

2021-04-01 21:55 UTC, kenetec commented on backend/api/views/messages.py
> +@messages.route("/all", methods=["GET"])
I would recommend keeping this as `/`  since it's a convention for REST and it'll be more understandable since we'll be able to grab all messages and any subset we want from this endpoint.

2021-04-05 23:54 UTC, AngelaLuo49021 approved these changes
Looks good, could you add screenshots of your Postman results to your PR and any future backend PR's

2021-04-06 00:19 UTC, kenetec approved these changes
Beautiful work!! 😍

2021-04-06 00:25 UTC, merged