Mentee Portal Setup
hack4impact-uiuc/mentee pull request #271
Opened 2021-04-01 18:57 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #number
 
## TODOs :star:
- [ ] Tests
- [ ] Documentation

2021-04-05 23:27 UTC, Leundai commented on frontend/src/components/App/App.js
> -      />
This was a duplicate component

2021-04-05 23:51 UTC, kenetec requested changes
Great work! 🤩 Good job on abstracting code out too, it really cleans up the code well. It's still a lil buggy due to the `usePersistenceState` I think, so you might have to edit that a bit.

2021-04-05 23:51 UTC, kenetec commented on frontend/src/utils/hooks/usePersistedState.js
> + */
Very cool! 🔥

2021-04-05 23:51 UTC, kenetec commented on frontend/src/utils/hooks/usePersistedState.js
> +  );
So one issue I noticed is that `ACCOUNT_TYPE.Admin` isn't being set, it might have to do with this shorthand if statement. Since `admin = 0` and `mentor = 1`, mentor will always be set instead of admin since JavaScript will see 1 as `true` and 0 as `false` if you don't explicitly check for a number.

2021-04-05 23:51 UTC, kenetec commented on frontend/src/components/pages/Login.js
> +    setPermissions(ACCOUNT_TYPE.ADMIN);
Can you use `setPermissions` on logout as well?

2021-04-05 23:52 UTC, AngelaLuo49021 approved these changes
Frontend is very pretty and looks just like faith's designs

2021-04-06 00:33 UTC, AngelaLuo49021 reviewed
Could you add a temporary button on the navbar to go to the mentee portal

2021-04-18 16:33 UTC, Leundai commented on frontend/src/components/pages/Login.js
> +    setPermissions(ACCOUNT_TYPE.ADMIN);
yessir

2021-04-20 00:02 UTC, kenetec approved these changes
Beautifull 😍

2021-04-20 00:03 UTC, kenetec commented
also merge to `dev` plz

2021-04-20 14:52 UTC, merged