Universal Signin Page
hack4impact-uiuc/mentee pull request #276
Opened 2021-04-09 03:14 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #274 
 
## TODOs :star:
- [ ] Tests
- [ ] Documentation

2021-04-13 21:45 UTC, Leundai commented on frontend/src/components/css/SelectLogin.scss
> +  margin-top: -15%;
lmk if this is something that is okay to do for css!

2021-04-14 08:04 UTC, Leundai commented on frontend/src/components/css/SelectLogin.scss
> +  margin-top: -15%;
Specifically the margin-top: -15%

2021-04-16 00:36 UTC, AngelaLuo49021 approved these changes
Looks good!

2021-04-18 06:18 UTC, kenetec requested changes
Awesome job!! 🥵 There's a few changes that I think should be made, lemme know if you have questions for any of them!

2021-04-18 06:18 UTC, kenetec commented on frontend/src/components/css/SelectLogin.scss
> +  margin-top: -15%;
yaa prolly fine,, wouldn't this be equivalent to `margin-bottom: 15%` though?

2021-04-18 06:18 UTC, kenetec commented on frontend/src/components/pages/Login.js
>              </NavLink>
The `Register` page can take in an `as` query to denote which kind of user to register as (based on the enum `ACCOUNT_TYPE`). I think you should reflect this here

2021-04-18 06:18 UTC, kenetec commented on frontend/src/components/pages/Login.js
> -                  setError(true);
These error messages give a bit more context to the user as sometimes an email might be sent to reset password. It's totally cool to redo they are set but I think they should still appear to the user.

2021-04-20 01:50 UTC, Leundai commented on frontend/src/components/css/SelectLogin.scss
> +  margin-top: -15%;
That didn't work :(

2021-04-20 15:23 UTC, kenetec approved these changes
GRavy 👶🏿

2021-04-21 18:52 UTC, merged