Update Frontend Appointments Flow
hack4impact-uiuc/mentee pull request #289
Opened 2021-04-16 04:34 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #268 
 
## TODOs :star:

2021-04-26 22:17 UTC, AngelaLuo49021 requested changes
![image](https://user-images.githubusercontent.com/42478474/116157816-398f9500-a6b3-11eb-932c-cb68230efe29.png)
This top part look a little whack

2021-04-29 23:58 UTC, kenetec approved these changes
sweeeet 🥧

2021-04-29 23:58 UTC, kenetec commented on backend/api/views/appointment.py
> +        start_time = appointment.timeslot.start_time.strftime(APPT_TIME_FORMAT + " GMT")
Try using `f'{APPT_TIME_FORMAT} GMT'` instead

2021-04-29 23:58 UTC, kenetec commented on frontend/src/components/MenteeAppointmentModal.js
> +    console.log(appointment);
Remove `console.log`

2021-04-30 02:41 UTC, AngelaLuo49021 approved these changes
Looks great!

2021-04-30 20:33 UTC, merged