Appointment request model
hack4impact-uiuc/mentee pull request #31
Opened 2020-10-15 21:39 UTC by nroy20

## Status: :construction: In development

## Description :star2:

Implementation of model for all requests for appointments for mentors.
Fixes #29
 
## TODOs :star:

2020-10-15 22:55 UTC, chyku requested changes

2020-10-15 22:55 UTC, chyku commented on backend/api/models/ApptRequest.py
> +    email = EmbeddedDocumentField(Email, required = True)
don't use the email document LOL it was only an example and should be fine as a string

2020-10-15 22:55 UTC, chyku commented on backend/api/models/ApptRequest.py
> +class ApptRequest(Document, Mixin):
hmm idk if it's necessary to abbreviate here

2020-10-15 22:55 UTC, chyku commented on backend/api/models/ApptRequest.py
> +        return f"""<name: {self.name}
include the name of the model here

2020-10-17 00:10 UTC, Leundai requested changes
Make sure to add your model to ```__init__.py``` 👍 
![image](https://user-images.githubusercontent.com/28935000/96323551-2a80a980-0fe3-11eb-82d7-9a55c117d216.png)

2020-10-20 14:53 UTC, chyku requested changes
and also export in __init__.py

2020-10-20 14:53 UTC, chyku commented on backend/api/models/AppointmentRequest.py
> +from api.models import Email
unnecessary import now

2020-10-20 14:53 UTC, chyku commented on backend/api/models/AppointmentRequest.py
> +    age = IntField(required=True)
now that we have age ranges, we can make this a string

2020-10-20 21:04 UTC, chyku requested changes
small things, otherwise looks good

2020-10-20 21:04 UTC, chyku commented on backend/api/models/AppointmentRequest.py
> +        return f"""<AppointmentRequest name: {self.name}
make sure to update these with the fields added, at least mentorid

2020-10-20 21:04 UTC, chyku commented on backend/api/models/__init__.py
> +from .AppointmentRequest import AppointmentRequest
not sure if you deleted the export, but you need to add appointmentrequest to `__all__`

2020-10-20 21:29 UTC, chyku approved these changes
lgtm

2020-10-21 21:50 UTC, Leundai approved these changes
Looks good

2020-10-21 21:59 UTC, merged