Mentee gallery
hack4impact-uiuc/mentee pull request #312
Opened 2021-05-06 01:08 UTC by IshaanRSharma

## Status:
:construction: In development

## Description :star2:
Mentee gallery for mentee cards.
![mentee gallery ](https://user-images.githubusercontent.com/44181424/117227931-c4b40d80-adcc-11eb-91f5-291966c97bab.png)

Fixes #288 
 
## TODOs :star:
1. getFilteredMentees isn't working when you filter by name or languages.

2021-05-11 16:27 UTC, AngelaLuo49021 requested changes

2021-05-11 16:27 UTC, AngelaLuo49021 commented on frontend/src/components/App/App.js
> +
the mentor gallery is broken on ur branch

![image](https://user-images.githubusercontent.com/42478474/117848254-be98b380-b248-11eb-9541-5cb158a02245.png)

2021-05-11 16:27 UTC, AngelaLuo49021 commented on frontend/src/components/App/App.js
> +      <Route
Can you also add a button to the navbar that goes to this link. Call it "Find a Mentee"

2021-05-11 16:27 UTC, AngelaLuo49021 commented on frontend/src/components/MenteeCard.js
> +  const [favorite, setFavorite] = useState(props.favorite);
remove the favorite or bookmark. This is not a feature for the mentee gallery

2021-05-11 16:27 UTC, AngelaLuo49021 commented on frontend/src/components/ModalInput.js
> +  // const returnDropdownItems = (items) => {
why is this commented out?

2021-05-11 16:27 UTC, AngelaLuo49021 commented on frontend/src/components/pages/Gallery.js
> +  const getFilteredMentees = useCallback(() => {
add filter by age range
![image](https://user-images.githubusercontent.com/42478474/117848767-3b2b9200-b249-11eb-9594-53d4c49b40ca.png)

2021-05-11 16:27 UTC, AngelaLuo49021 commented on frontend/src/components/pages/Gallery.js
> +            // getFilteredMentors().map((mentor, key) => (
delete commented out code that is no longer relevant

2021-05-18 19:06 UTC, AngelaLuo49021 requested changes
correct:
![image](https://user-images.githubusercontent.com/42478474/118709056-21a6bf00-b7e2-11eb-989a-c65ef0b5b546.png)
incorrect
![image](https://user-images.githubusercontent.com/42478474/118709162-413de780-b7e2-11eb-82c7-a665fe453c35.png)

you changed the background to white on both galleries??? the filter bar should be the only thing that is yello

2021-05-21 02:34 UTC, AngelaLuo49021 requested changes
![image](https://user-images.githubusercontent.com/42478474/119073464-04751a80-b9b3-11eb-8913-2ae3513cad7e.png)
the location and languages font became black and text became centred for some reason??? The centering issue is also on the mentor gallery

2021-06-01 01:07 UTC, kenetec requested changes
Great job!! 🤩there's just a few changes that you need to make and then you are good!

2021-06-01 01:07 UTC, kenetec commented on frontend/src/components/ModalInput.js
>          );
I think there are supposed to be dropdown items for the Mentor Gallery 
![image](https://user-images.githubusercontent.com/10099821/120252848-52a7da80-c24b-11eb-81ef-1e331d2cadae.png)

2021-06-01 01:07 UTC, kenetec commented on frontend/src/components/pages/MenteeGallery.js
> +        console.log("sets list ");
Remove `console.log`

2021-06-01 01:07 UTC, kenetec commented on backend/api/models/MentorApplication.py
> +    languages = StringField(required=True)
This will probably break any fetch for applications since the existing applications use a `ListField` so if that happens, you'll most likely need to remove the existing objects in the db.

2021-06-01 01:09 UTC, kenetec commented on package.json
> +        "react-dropzone": "^11.3.2"
I think you added these dependencies to the root folder, these should go in the frontend if they are necessary. Since everything seems to work right now I think you can remove them

2021-06-04 00:45 UTC, AngelaLuo49021 approved these changes
Looks good!

2021-06-09 05:17 UTC, kenetec approved these changes
love ittt 😍

2021-06-09 05:28 UTC, merged