Mentee admin portal display
hack4impact-uiuc/mentee pull request #321
Opened 2021-05-19 16:27 UTC by Leundai

## Status: :construction: In development

## Description :star2:

Fixes #302 
 
## Screenshots
![image](https://user-images.githubusercontent.com/28935000/118849219-211b3080-b895-11eb-85d6-182e6da8f1b1.png)

2021-05-21 01:47 UTC, AngelaLuo49021 requested changes
Can you remove the columns entirely of video posted, appoitnments available, and profile pic up?

Also it do be kinda ugly but if its intuitive then its fine bc our timeline is tighter.

2021-05-28 17:52 UTC, AngelaLuo49021 approved these changes
Looks great! I think you to commit your yarn.lock

2021-05-31 21:00 UTC, Leundai commented
@AngelaLuo49021  Yup! I meant to commit it since I added a new library for json display

2021-05-31 23:35 UTC, kenetec approved these changes
Great work!! The main change you should make is to use const variables in `api.js`

2021-05-31 23:35 UTC, kenetec commented on frontend/src/components/AdminDataTable.js
> +        rowExpandable: (account) => account.is_private,
Should this be `not account.is_private` instead?

2021-05-31 23:35 UTC, kenetec commented on frontend/src/components/pages/AdminAccountData.js
> +      console.log(menteeRes);
Remove `console.log`

2021-05-31 23:35 UTC, kenetec commented on frontend/src/components/pages/AdminAccountData.js
> +        setFilterData(mentorRes.mentorData);
(No change required) At this point it's probably a good idea to start switching towards some sort of state management system (Redux or MobX), as this startup function is causing 4 re-renders.

2021-05-31 23:35 UTC, kenetec commented on frontend/src/utils/api.js
> +};
Let's use const variables for these. Also this can be abbreviated to `=> await fetchAppointmentsByType([type])`

2021-06-04 00:09 UTC, Leundai commented on frontend/src/components/AdminDataTable.js
> +        rowExpandable: (account) => account.is_private,
I think it is meant to be expandable only if the profile is private since that profile does not exist in the public domain of gallery

2021-06-04 00:11 UTC, Leundai commented on frontend/src/components/pages/AdminAccountData.js
> +        setFilterData(mentorRes.mentorData);
Noted. This for sure will be one of the main things we'll need to switch over for next semester

2021-06-05 02:25 UTC, merged