Mentor Portal Appointments
hack4impact-uiuc/mentee pull request #35
Opened 2020-10-15 23:10 UTC by Leundai

## Status: :construction:

## Description :star2:

Fixes #26 
Currently merged from the work that has been made by @Feeshay  

Screenshots will come in soon!
 
## TODOs :star:

2020-10-24 20:44 UTC, Lam7150 commented on frontend/src/components/pages/Appointments.js
> +  },
do we need an id or key here? especially since the "key" value is the same as the key. Looking at the rest of the code, it seems the only relevant/useful field here is 'title', but correct me if I'm wrong

2020-10-24 20:45 UTC, Lam7150 commented on frontend/src/components/pages/Appointments.js
> +                  {appointmentsObject["date"]}
do we prefer dot notation or bracket notation here? @chyku

2020-10-24 20:48 UTC, Lam7150 commented on frontend/src/components/pages/Appointments.js
> +          borderLeft: "3px solid #E5E5E5",
i would export this style into a 'styles' const object at the bottom of the file for more descriptive purposes (similar to css but in js object form). Then you can do style={styles.sidebar} here to be more meaningful. Check out React Native Stylesheets as a reference (not in react)

2020-10-24 20:48 UTC, Lam7150 commented on frontend/src/components/css/Appointments.scss
> +    background: #FCF6E8;
let's start putting these colors into a utils file!

2020-10-26 00:55 UTC, Leundai commented on frontend/src/components/pages/Appointments.js
> +  },
That is true it is also very redundant! Thanks!

2020-10-26 00:55 UTC, Leundai commented on frontend/src/components/pages/Appointments.js
> +          borderLeft: "3px solid #E5E5E5",
Got it! 👍

2020-10-27 02:44 UTC, chyku requested changes
:100:

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/css/Appointments.scss
> +    font-weight: 700;
does this change anything? idk if this is even from this branch bc i think other branches are mixed into here

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/css/Appointments.scss
> +    background: #FCF6E8;
if you don't take the issue someone else is going to have to LOL

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/css/Appointments.scss
> +}
newline at the end here?

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/css/Navigation.scss
> +}
same newline thing

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +const declineIcon = () => <img src={DeclineIcon} />;
why are these functions that return that instead of just variables that are what the function returns? like why is it not `upcomingIcon = <img src={AppointmentUpcoming} />;`

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +                  {appointmentsObject["date"]}
idk if there's much of a difference but it is a little weird to have it not be consistent across the file (and repo in general)

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +  const Appointments = (props) => {
instead of just passing in props you can use [object destructuring](https://medium.com/@lcriswell/destructuring-props-in-react-b1c295005ce0) (cont)
```suggestion
  const Appointments = ({data}) => {
```

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +          {props.data.map((appointmentsObject, index) => (
(cont) and then just:
```suggestion
          {data.map((appointmentsObject, index) => (
```

2020-10-27 02:44 UTC, chyku commented on frontend/src/resources/appointments.json
> +        {
Generally when you make example data for your component you should delete it when you merge into master- treat it as if you're merging into a prod environment and don't include files that you'll need to delete later

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +        return <Appointments data={appointmentData["past"]} />;
not sure what this is going to look like in the future, but since the appointmentData keys are the same as the tab keys, you could have this fall through for upcoming, pending, and past and pass in data depending on the tab key so that you only have the `return <Appointments data={appointmentData[tab.key]} />;`

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +    if (tab.id === 1) {
why did you choose to use id to check here? IMO using the key is more intuitive to see what's going on and i don't think you're using the id field anywhere else, so if you change that you can delete the ids out of the tabs obj

2020-10-27 02:44 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +          <div className="appointments-welcome-text">Welcome, {"Bernie"}</div>
the mentor name should still be a TODO here

2020-10-27 02:53 UTC, Leundai commented on frontend/src/components/css/Appointments.scss
> +}
Wait wdym by if someone I don't take the issue

2020-10-27 02:58 UTC, Leundai commented on frontend/src/components/pages/Appointments.js
> +const declineIcon = () => <img src={DeclineIcon} />;
Antd expects a function of the sort for the prop icon. But I'm not too sure if there is another workaround..
![image](https://user-images.githubusercontent.com/28935000/97251588-2bc98780-17d6-11eb-9052-f5fbd71941e0.png)
![image](https://user-images.githubusercontent.com/28935000/97251687-54518180-17d6-11eb-9f81-f40a6459f3dd.png)

2020-10-27 18:41 UTC, AngelaLuo49021 requested changes

2020-10-27 18:41 UTC, AngelaLuo49021 commented on frontend/src/components/css/Appointments.scss
> +.appointments-background {
![image](https://user-images.githubusercontent.com/42478474/97346825-f2d2f680-1859-11eb-894a-d9e9e8776981.png)
![image](https://user-images.githubusercontent.com/42478474/97346853-ffefe580-1859-11eb-8bd5-e4cb19501917.png)
Can we add the gap in the designs between the tabs and the appointments list

2020-10-27 20:14 UTC, chyku requested changes

2020-10-27 20:14 UTC, chyku commented on frontend/src/resources/appointments.json
> +        {
hello are you going to remove this

2020-10-27 20:14 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +// TODO: Clean this make it easy for people to figure out and remove certain elements
also what does this mean? figure out and remove what elements

2020-10-27 20:14 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +const declineIcon = () => <img src={DeclineIcon} />;
ohh so it has to be a component. idk if you heard but angela also said it's okay to use the [ANT design icons](https://ant.design/components/icon/), so if you want to replace these with those that also works

2020-10-27 20:51 UTC, AngelaLuo49021 requested changes

2020-10-27 20:51 UTC, AngelaLuo49021 commented on frontend/src/components/pages/Appointments.js
> +const upcomingIcon = () => <img src={AppointmentUpcoming} />;
tiny thing, designs changed and now it looks more like an info button 
![image](https://user-images.githubusercontent.com/42478474/97360415-2dde2580-186c-11eb-90a1-e0f0c6f14214.png)

2020-10-27 21:30 UTC, Lam7150 approved these changes
Looks good!

2020-10-27 21:37 UTC, AngelaLuo49021 approved these changes
Looks good!

2020-10-27 22:07 UTC, chyku approved these changes
did u change the title to ready freddy to get my attention

2020-10-27 22:18 UTC, merged