🔢 Change Homepage button based on user
hack4impact-uiuc/mentee pull request #350
Opened 2021-09-23 02:18 UTC by zfaizal2

## Status: 🚧 

## Description :star2:

Fixes #348 
![image](https://user-images.githubusercontent.com/3940879/134445755-f49f4203-1439-43b0-b70a-f5ee104423df.png)

 
## TODOs :star:

2021-09-24 00:09 UTC, Leundai requested changes
lookin good

2021-09-24 00:09 UTC, Leundai commented on .gitignore
> +package.json
we should track this just in case there are some changes. This won't be automatically changed by yarn

2021-09-30 22:54 UTC, pguduguntla reviewed
Looks good to me.

2021-10-01 21:34 UTC, Leundai approved these changes
looks good!

2021-10-01 21:34 UTC, Leundai commented on frontend/src/components/pages/Home.js
> +              }
A super small thing, could you add these as a const to the file `consts.js`

2021-10-05 01:39 UTC, pguduguntla approved these changes
Looks good.

2021-10-05 17:45 UTC, merged