🥯  Favorite contacts bug fix
hack4impact-uiuc/mentee pull request #352
Opened 2021-09-23 21:03 UTC by lucianatl

## Status:

## Description :star2:

- when there are no favorited contacts, displays "no favorited contacts" instead of spinning icon 
![image](https://user-images.githubusercontent.com/55062455/134582805-ac060d5c-4161-40ed-8019-6481fa87e366.png)
Fixes #343
 
## TODOs :star:

2021-09-23 23:57 UTC, Leundai requested changes

2021-09-23 23:57 UTC, Leundai commented on frontend/src/components/BookmarkSidebar.js
> +        <Spin spinning={!bookmarks} className="bookmark-spin">
Before we used to have a spinning indicator when bookmarked mentors are loading. However now it only shows "No favorite contacts" instead of the loading signal.

I think for this it might be best to add another prop param in the bookmark component that is visible while the useEffect is calling the API from `MenteeAppointments.js`.

2021-09-23 23:57 UTC, Leundai commented on frontend/src/components/BookmarkSidebar.js
> +          >
Just for now, I think we should have the text centered instead of anchored to the side. Also, we can say "No favorited Mentors"

2021-09-23 23:57 UTC, Leundai commented on frontend/src/components/BookmarkSidebar.js
> +          <div
Also, we can have some conditional rendering here instead of css display usage. But lmk if that doesn't work.

2021-09-30 22:09 UTC, nroy20 commented
looks good!

2021-09-30 22:11 UTC, nroy20 approved these changes
looks good!

2021-10-01 21:37 UTC, Leundai approved these changes
gravy

2021-10-02 01:21 UTC, merged