adding tabs to calendar page
hack4impact-uiuc/mentee pull request #36
Opened 2020-10-16 19:11 UTC by Lam7150

## Status: :construction: In development

## Description :star2:

Fixes #22 
 
## TODOs :star:

2020-10-20 21:00 UTC, chyku requested changes

2020-10-20 21:00 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +  function renderTab(tab) {
useEffect

2020-10-20 21:03 UTC, Lam7150 commented on frontend/src/components/css/Appointments.scss
> +    font-weight: 700;
oh that's just the standard **bold** text weight (700), 400 is average

2020-10-20 21:05 UTC, Lam7150 commented on frontend/src/components/pages/Appointments.js
> +    };
Ok so for this Michael and I tried to figure out how to use css for this, but with this Button Antdesign component the only way to override the style is to use inline styling, that's why it's written like this, i'm not sure if scss is possible here

2020-10-20 21:06 UTC, Lam7150 commented on frontend/src/components/pages/Appointments.js
> +            <Calendar></Calendar>
my B

2020-10-20 21:06 UTC, AngelaLuo49021 commented on frontend/src/components/css/Appointments.scss
> +    color: #A58123;
Also can you make the background color white like the designs?

2020-10-20 21:06 UTC, Lam7150 commented on frontend/src/components/pages/Appointments.js
> +  function renderTab(tab) {
I was thinking about this, but how would we use useEffect here?

2020-10-20 21:07 UTC, Lam7150 commented on frontend/src/components/css/Appointments.scss
> +    color: #A58123;
Leo's gonna make the background white in his PR

2020-10-20 21:19 UTC, chyku requested changes

2020-10-20 21:19 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +  function renderTab(tab) {
actually scratch this idea, you could also just put this entire function into rendering since it should re render on each state change

2020-10-20 21:19 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +      {renderTab(currentTab)}
what i was talking about above
```suggestion
      { switch (tab) {
      case Tabs.upcoming:
        return <UpcomingTab />;
      case Tabs.pending:
        return null;
      case Tabs.past:
        return null;
      case Tabs.availability:
        return <AvailabilityTab />;
      default:
        return <div />;
    }
    }
```

2020-10-20 21:19 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +    };
can u put these as consts earlier in the file then so we can change them without digging deep into this file

2020-10-20 21:19 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +      <div className="appointments-welcome-text">Welcome, Bernie</div>
need to make a note here to not leave it for bernie

2020-10-20 21:19 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +        <Tab title={Tabs.availability} text="Appointments" />
nit but can this be turned into a map on Tab? not a huge fan of hardcoding these

2020-10-20 21:19 UTC, chyku commented on frontend/src/components/css/Appointments.scss
> +    font-weight: 700;
why not use `font-weight: bold;`?

2020-10-20 21:24 UTC, Lam7150 commented on frontend/src/components/css/Appointments.scss
> +    font-weight: 700;
i could do that too, l'll change it

2020-10-20 21:31 UTC, Feeshay commented on frontend/src/components/pages/Appointments.js
> +    };
we could also override the default button styling, which might not be that bad of an option since all our buttons will look pretty similar

2020-10-20 22:20 UTC, Lam7150 commented on frontend/src/components/pages/Appointments.js
> +      {renderTab(currentTab)}
wdym here? imo it'd be cleaner to put the switch statement into a function

2020-10-20 23:00 UTC, Leundai commented on frontend/src/components/css/Appointments.scss
> +    color: #A58123;
Ye

2020-10-22 02:41 UTC, chyku approved these changes
looks good for now, making issues for some comments here

2020-10-22 02:41 UTC, chyku commented on frontend/src/components/pages/Appointments.js
> +      {renderTab(currentTab)}
lmao i think it's sus to call a function in render like that but i can't find any direct evidence for it being bad so it's fine

2020-10-22 21:25 UTC, Leundai approved these changes
Lookin good

2020-10-22 21:27 UTC, merged