🧑🏻 Contact Me modal improvements
hack4impact-uiuc/mentee pull request #403
Opened 2021-10-28 22:07 UTC by nroy20

## Status:

## Description :star2:

Fixes #389 and #390

Updated Contact Me modal to include new fields (added preferred method of contact + interest areas); modified sendMenteeMentorEmail() , messages.py endpoint, and SendGrid template to account for changes.

Changed messages.py, MentorContactModal.js, and api.js
## TODOs :star:

2021-11-02 23:21 UTC, pguduguntla commented on frontend/src/components/MentorContactModal.js
> -                console.log("Failed to send message");
do we wanna remove these prints statements?

2021-11-02 23:23 UTC, pguduguntla commented on frontend/src/components/MentorContactModal.js
> +            )}
So, in terms of the error message, I actually added a field inside ModalInput where you can pass in an error = True and errorMessage props. I would  consider looking at how I implemented it in EditProfile or any of the registration components to see how to implement it. I think it'll make it more consistent.

2021-11-02 23:23 UTC, pguduguntla commented on frontend/src/components/MentorContactModal.js
> +                  console.log("Failed to send message");
keep print statement?

2021-11-02 23:24 UTC, pguduguntla commented on package.json
> +    "dependencies": {}
Remove this change

2021-11-02 23:26 UTC, pguduguntla requested changes
Comments above^. Only thing i have is to pass the error/errorMessage into <ModalInput /> as a prop. You'll have to add a custom onChange function as well.

2021-11-02 23:54 UTC, zfaizal2 approved these changes
simple styling changes, but works fine!

2021-11-02 23:54 UTC, zfaizal2 commented on frontend/src/components/MentorContactModal.js
> +            label="radio"
adjust label to reflect the name

2021-11-02 23:54 UTC, zfaizal2 commented on frontend/src/components/MentorContactModal.js
> +        <h1>Reach Out to {mentorName}</h1>
modify CSS for modal

![image](https://user-images.githubusercontent.com/3940879/139966840-136c1366-741c-4381-a086-704a89cfe87a.png)

2021-11-29 21:03 UTC, Lam7150 approved these changes

2021-11-29 21:03 UTC, merged