Tweak nav styling
hack4impact-uiuc/mentee pull request #44
Opened 2020-10-20 21:22 UTC by Feeshay

## Status:
:rocket: Ready

## Description :star2:
* Use view height in some places instead of hardcoding pixels
* Fix menu item spacing and get rid of annoying gray bar in random places
* Add shadow to sidebar
* Add profile CSS file

2020-10-20 22:57 UTC, Leundai approved these changes
Looks good!

2020-10-22 21:36 UTC, AngelaLuo49021 requested changes
Looks gucci overall! Just remove that one rounded border I just talked to faith about and merge in lam's changes from master

2020-10-22 21:36 UTC, AngelaLuo49021 commented on frontend/src/components/css/Navigation.scss
> +    border-radius: 0px 8px 8px 0px;
Remove the rounded borders

2020-10-22 21:52 UTC, AngelaLuo49021 approved these changes
very purty!

2020-10-22 21:52 UTC, merged