Get appointment request
hack4impact-uiuc/mentee pull request #45
Opened 2020-10-20 21:28 UTC by nroy20

## Status: :construction: In development

## Description :star2:

Created a GET request that returns all requested appointments for the specified mentor given their id.
Fixes #39 
 
## TODOs :star:
- [ ] Tests
- [ ] Documentation
- [ ] Reviews

2020-10-22 21:30 UTC, chyku commented on backend/api/views/main.py
> +@main.route("/requests/<string:mentor_id>", methods=["GET"])
wanted to note that we want this in a separate file for requests (another file in views that someone else is adding)

2020-10-27 20:27 UTC, chyku requested changes
idk if this is ready bc the pr desc still has in dev but i have comments LOL

2020-10-27 20:27 UTC, chyku commented on backend/api/views/appointment.py
> +def get_requests(mentor_id):
can this be clearer that it gets appointments by mentor ID in the endpoint URL & request function name (as opposed to appointment request ID or something)

2020-10-27 20:27 UTC, chyku commented on backend/api/views/main.py
> +
lol why is this in this PR

2020-10-27 20:56 UTC, chyku approved these changes
:heart_decoration:

2020-10-28 21:27 UTC, chyku submitted a review, later dismissed

2020-10-28 21:27 UTC, chyku commented on backend/api/views/appointment.py
> +=======
lol i think you merged this wrong

2020-10-28 21:27 UTC, chyku commented on backend/api/views/appointment.py
> +=======
if u delete this it's an insta approve

2020-10-29 21:14 UTC, Leundai approved these changes

2020-10-29 21:41 UTC, AngelaLuo49021 approved these changes
Look good!

2020-10-29 21:45 UTC, merged