add appointment.py file
hack4impact-uiuc/mentee pull request #46
Opened 2020-10-20 21:30 UTC by AzureQDragon

## Status:
:construction: In development

## Description :star2:
Creates endpoint for PUT request for mentee appointments
Fixes #41 
 
## TODOs :star:
- [ ] Write endpoint
- [ ] Tests
- [ ] Documentation

2020-10-22 22:56 UTC, chyku requested changes
small things

2020-10-22 22:56 UTC, chyku commented on backend/api/views/appointment.py
> +from api.models import db, Person, Email, Availability, AppointmentRequest
don't need to import anything but AppointmentRequest here

2020-10-22 22:56 UTC, chyku commented on backend/api/views/appointment.py
> +    # Try to get appointment
Unnecessary comment lol

2020-10-22 22:56 UTC, chyku commented on backend/api/views/appointment.py
> +    appointment.accepted = data.get("accepted", appointment.accepted)
if you change this endpoint to be just for accepting the appt, you don't have to pass in a field at all but just set it to true

2020-10-22 22:56 UTC, chyku commented on backend/api/views/appointment.py
> +@appointment.route("/appointment/<id>", methods=["PUT"])
this has a one-time specific use, so you can change the endpoint name/function name to be more specific to accepting the appointment

2020-10-23 18:09 UTC, chyku requested changes
tiny tiny things but otherwise looks good

2020-10-23 18:09 UTC, chyku commented on backend/api/views/appointment.py
> +@appointment.route("/accept/<id>", methods=["PUT"])
wait i meant "appointments/accept/<id>" LOL we should keep it realted to appointments

2020-10-23 18:09 UTC, chyku commented on backend/api/views/appointment.py
> +    # Update appointment acceptance status
smallest nitpick ever but i think this is straightforward enough to not need this comment

2020-10-23 19:41 UTC, Leundai reviewed
Overall it is looking good :) I'll wait until the changes are implemented then I'll approve

2020-10-23 19:41 UTC, Leundai commented on backend/api/views/appointment.py
> +@appointment.route("/accept/<id>", methods=["PUT"])
If we're using "appointments" plural as our endpoint should we also change the file name too? along with the blueprint?

2020-10-23 21:10 UTC, AzureQDragon commented on backend/api/views/appointment.py
> +@appointment.route("/accept/<id>", methods=["PUT"])
I think the file name is supposed to be appointment. As for making the endpoint plural I don't think it really matters since it's referencing one appointment every time

2020-10-26 00:58 UTC, Leundai commented on backend/api/views/appointment.py
> +from dateutil.parser import parse
These might not be needed anymore since they were used for testing.

2020-10-26 00:58 UTC, Leundai commented on backend/api/views/appointment.py
> +    logger.info("Data received: %s", data)
I'm not sure if these will be needed either since this PUT request just takes in the ID for a specific appointment and changes that appointment object.

2020-10-27 02:51 UTC, chyku approved these changes
lets get this BREAD

2020-10-27 18:43 UTC, AngelaLuo49021 approved these changes
Looks great daniel!!!!

2020-10-27 18:43 UTC, merged