Post mentee appointments
hack4impact-uiuc/mentee pull request #55
Opened 2020-10-23 06:46 UTC by Leundai

## Status: :rocket:

## Description :star2:

Fixes #40 
Following the same convention as #5 **POST Request mentor profiles** I added WTFormssupport for appointments as well. Overall creating a clean endpoint.

When creating the POST request, I used the same naming and spelling as that of the database model that is defined at #31 

I also ran into a bug that slipped through my previous PR with WTForms for #17 where whenever I sent a value false for the field "accepted" or in previous BooleanField in #17 it would not accept it. This is because BooleanField in WTForms requires a definition of what is a 'false' value. This has been fixed 😄 
## Screenshots:
### Postman
![image](https://user-images.githubusercontent.com/28935000/96965083-2f58c800-14d1-11eb-89a7-9f19fe3c7176.png)
### MongoDB 
![image](https://user-images.githubusercontent.com/28935000/96965227-68913800-14d1-11eb-82f5-dfc6da7dabcb.png)

## TODOs :star:
- [x] Tests
- [x] Documentation
- [x] Screenshots

2020-10-23 17:11 UTC, AzureQDragon requested changes

2020-10-23 17:11 UTC, AzureQDragon commented on backend/api/views/main.py
> +# POST request for Mentee Appointment
I think you need to move the appointment requests to a new file called appointment.py

2020-10-23 18:25 UTC, Leundai commented on backend/api/views/main.py
> +# POST request for Mentee Appointment
Ah gotcha a new blueprint! Thanks!

2020-10-27 03:09 UTC, chyku reviewed
idk if i want to request changes for this since it looks good but i want you to look at the comments before you push it

2020-10-27 03:09 UTC, chyku commented on backend/api/utils/request_utils.py
> +class EducationForm(Form):
tbh im just gonna trust u on these validation forms

2020-10-27 03:09 UTC, chyku commented on backend/api/views/appointment.py
> +        print("returning!")
print statement??

2020-10-27 03:09 UTC, chyku commented on backend/api/views/appointment.py
> +        return create_response(status=422, message="Missing fields " + msg)
I think something cool you could do is to extract into a utility function in utils since it is repeated from the other put requests

2020-10-27 03:25 UTC, Leundai commented on backend/api/views/appointment.py
> +        print("returning!")
LOL

2020-10-27 03:26 UTC, Leundai commented on backend/api/utils/request_utils.py
> +class EducationForm(Form):
Don't worry I'm gonna write test cases for these weird things

2020-10-27 20:33 UTC, chyku approved these changes
:small_airplane:

2020-10-27 20:33 UTC, chyku commented on backend/api/views/appointment.py
> +def create_appointment():
something that i just noticed that's throwing me off is that these are appt requests, not actual appointments & this file & endpoint make it seem like they're just appointments, but this is not worth blocking a PR for

2020-10-27 21:10 UTC, AngelaLuo49021 approved these changes
Look great leo!

2020-10-27 21:11 UTC, merged