Removed examples and example files
hack4impact-uiuc/mentee pull request #56
Opened 2020-10-26 01:40 UTC by Leundai

## Status: :rocket:

## Description :star2:

Fixes #51 
Super quick removal 😄 
Lowkey, I feel like after our MVP we should implement unit testing for our endpoints and frontend too.

2020-10-26 01:52 UTC, mc578 approved these changes
thank you

2020-10-26 01:54 UTC, Feeshay approved these changes
thank you
also I hate using github with 2 accounts :/

2020-10-27 02:46 UTC, chyku requested changes
tiny thing

2020-10-27 02:46 UTC, chyku commented on backend/api/views/auth.py
> -    return create_response(data={results.json()})
don't delete this this is for the auth server

2020-10-27 02:46 UTC, chyku commented on backend/api/views/auth.py
> +from api.models import db
this is fine to keep though

2020-10-27 20:41 UTC, chyku requested changes
another thing i missed

but wrt unit testing, maybe i have too much of a move fast mindset but i don't see much value in backend unit testing for a relatively straightforward small scale CRUD app. we're also pretty limited on time and i'd rather have us develop more features (or to finish what we want to in the first place!) than to move backwards and test get/delete endpoints when in reality they won't fail all that easily. 

i also am not a fan of frontend testing for small apps because unless several teams are using the same components and then someone changes that component & a jest snapshot fails (basically jest just takes "snapshots" of components in the current instance and if it changes, the snapshot test fails and you have to manually update it yourself) they can check to see if they broke anything.

2020-10-27 20:41 UTC, chyku commented on backend/api/models/User.py
> -from flask_mongoengine import Document
ALSO don't delete this mb user is also auth stuff

2020-10-28 21:26 UTC, chyku approved these changes
:+1:

2020-10-28 22:14 UTC, merged