Delete appointment request
hack4impact-uiuc/mentee pull request #57
Opened 2020-10-27 19:27 UTC by nroy20

## Status:

## Description :star2:

Fixes #number
 
## TODOs :star:

2020-10-27 20:03 UTC, AzureQDragon approved these changes
Looks good!

2020-10-27 21:15 UTC, chyku requested changes

2020-10-27 21:15 UTC, chyku commented on backend/api/views/appointment.py
> +    return create_response(data={"requests": requests})
we should wait until the get request gets merged in, merge master into this so you can resolve this bc it's not supposed to be here

2020-10-27 21:15 UTC, chyku commented on backend/api/views/appointment.py
> +    return create_response(data={"deleted id": appointment_id})
there's no need to return the deleted appt id, the frontend probably wouldn't use it for anything

2020-10-30 14:33 UTC, chyku approved these changes

2020-10-30 14:33 UTC, chyku commented on backend/api/views/appointment.py
> +    return create_response(status=200, message=f"Success")
you don't need to specify the status if it's a 200, that's the default in [the defintion of create_response](https://github.com/hack4impact-uiuc/mentee/blob/master/backend/api/core.py#L28)

2020-10-31 20:09 UTC, merged