Mentor Gallery Page
hack4impact-uiuc/mentee pull request #59
Opened 2020-10-27 20:21 UTC by AzureQDragon

## Status:
:construction: In development

## Description :star2:
Creates cards on the mentor gallery page.

Fixes #52 
 
## TODOs :star:
- [ ] Create cards
- [ ] Populate page with cards
- [ ] Tests
- [ ] Documentation

2020-10-28 22:52 UTC, AngelaLuo49021 requested changes

2020-10-28 22:52 UTC, AngelaLuo49021 commented on frontend/src/components/App/App.js
> +          <Navigation content={<MentorGallery />} page="mentorgallery" />
We'll need to use the Mentee navigation bar once @Feeshay  get thats in

2020-10-28 22:52 UTC, AngelaLuo49021 commented on frontend/src/components/css/MentorGallery.scss
> +
remove blank line

2020-10-28 22:52 UTC, AngelaLuo49021 commented on frontend/src/components/pages/MentorGallery.js
> +function MentorCard({
- Increase the space between"in person | virtual " and Location,
- Increase the space between Location and Specialization, 
- Increase the space between Specialization and links (keep the linkedin and website links still close together tho like how they are now)
- Increase the space between the links and the yellow line above "View Profile" button
- Basically we want the Mentor Card to look more long and less square
- For the website and linkedin links. Add more space between the icon and the actual link. Also increase the icon size and make the text grey instead of blue

2020-10-29 23:00 UTC, Feeshay commented on frontend/src/resources/default-picture.svg
> +<svg width="93" height="92" viewBox="0 0 93 92" fill="none" xmlns="http://www.w3.org/2000/svg">
you can use an avatar like in the Profile page for consistency: <Avatar icon={<UserOutlined />} />

2020-10-30 14:39 UTC, chyku requested changes

2020-10-30 14:39 UTC, chyku commented on frontend/src/components/pages/MentorGallery.js
> +            <Title type="secondary" style={{ margin: 0 }} level={5}>
you should create a style for this so it doesn't have to be hardcoded into every single title like is done in the [appointments page](https://github.com/hack4impact-uiuc/mentee/blob/master/frontend/src/components/pages/Appointments.js#L212)

2020-10-30 14:39 UTC, chyku commented on frontend/src/components/pages/MentorGallery.js
> +          <LinkedinOutlined style={{ fontSize: "20px" }} />
same here with styling

2020-10-30 14:39 UTC, chyku commented on frontend/src/resources/specialization.svg
> +<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
this was prob one of the designs made not using antd icons, i'm fine with either but id prefer antd icons for consistency tbh

2020-10-30 14:39 UTC, chyku commented on frontend/src/components/pages/MentorGallery.js
> +      name: "test",
can you put a quick "TODO" comment here so that we know to populate this with a mentor GET request

2020-10-30 19:16 UTC, chyku requested changes
looks generally good, although you should test whether it still displays fine without some optional fields (IMO linkedin & website shouldn't be required but we can discuss this later)

2020-10-30 19:16 UTC, chyku commented on frontend/src/components/pages/MentorGallery.js
> +  }
u should delete this lol

2020-10-30 19:16 UTC, chyku commented on frontend/src/components/pages/MentorGallery.js
> +  if (picture == null) {
imo a cleaner check instead of `== null` is `if (!picture)`, so this also covers all falsy javascript values like empty strings

2020-10-31 04:41 UTC, AngelaLuo49021 commented on frontend/src/components/App/App.js
>            <Navigation content={<Gallery />} page="gallery" needsAuth={false} />
Why is there both "Gallery" and "MentorGallery"? I think you should just be replacing the <Gallery > with <MentorGallery /> instead of making a separate route below. Also you would need needsAuth={false}

2020-10-31 20:51 UTC, chyku approved these changes
looks generally fine except the warning signs for scss (we should've used modules for it but it was giving me issues when i was setting it up), address @AngelaLuo49021 's comments and we should be alright

2020-10-31 20:51 UTC, chyku commented on frontend/src/components/css/MentorGallery.scss
> +.links:hover{
be careful when you're naming your css classes. if they overlap with anyone else's css, it'll get messed up

2020-10-31 20:51 UTC, chyku commented on frontend/yarn.lock
> +  integrity sha512-y9DvdSti8NnYB9Be92ddMZQrcOe04kcQtcxtBx4NkB04+qZ+JUWotnXBJTmxlKudhxNTQ3RRknMwNU2YQl/Org==
this is such a random change but alright

2020-11-01 00:30 UTC, AngelaLuo49021 approved these changes
Looks good!

2020-11-01 01:20 UTC, merged