API Wrapper
hack4impact-uiuc/mentee pull request #66
Opened 2020-10-28 21:25 UTC by Leundai

## Status: :construction:

## Description :star2:

Fixes #62 
Used [YMCA](https://github.com/hack4impact-uiuc/ymca/blob/master/client/src/utils/api.js) project as a reference in creating the API wrapper.
The overall structure is based around [Axios](https://www.npmjs.com/package/axios) in which we create promises and call the backend then finally return the data that was sent as an object. 

The execution of how I implemented this data into the MentorProfile page was similar to that of [YMCA's components](https://github.com/hack4impact-uiuc/ymca/blob/master/client/src/components/desktop/ResourceDetail.js)
 
## Screenshots
![image](https://user-images.githubusercontent.com/28935000/97498357-0a81ac00-193a-11eb-8606-ed81e91f291a.png)

## TODOs :star:
- [ ] Create functions for api calls
- [ ] Implement into a component
- [ ] Test
- [ ] Screenshots

2020-10-28 22:44 UTC, chyku commented on frontend/src/utils/api.js
> +      return null;
u probably got a lot of this from ymca, but do these have to return anything?

2020-10-28 22:44 UTC, chyku commented on frontend/src/utils/api.js
> +// Endpoint has not been merged yet. Remove this once it is
what does this mean- this hasn't been merged into where?

2020-10-28 22:59 UTC, Leundai commented on frontend/src/utils/api.js
> +// Endpoint has not been merged yet. Remove this once it is
into the main branch. I'll clarify that. Not sure if this is necessary but it'll be just so that I'm aware that this won't work yet.

2020-10-29 21:36 UTC, chyku requested changes
more comments

2020-10-29 21:36 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +  });
don't structure this with checking if mentor was fetched already or not, just pass in an empty dependency array as the second argument to useEffect. it'll just run when the component displays for the first time

2020-10-29 21:36 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +    return educations[0] != null ? (
sus check here, what if educations is null itself

2020-10-29 22:33 UTC, Leundai commented on frontend/src/utils/api.js
> +      return null;
Probably not the post requests or things that send data instead of receiving

2020-10-29 22:37 UTC, Leundai commented on frontend/src/components/pages/Profile.js
> +    return educations[0] != null ? (
Added! Once the educations field in the backend gets sent as a list we can change this up. I'll add a comment here so that whoever takes up that issue we can refer to it

2020-10-30 14:31 UTC, chyku requested changes
also, can you add a screenshot of the mentor's data in the db? the education in your screenshot has the undefined in there and it looks sus

2020-10-30 14:31 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +      : in_person || group_session;
what is this supposed to do? `in_person` and `group_session` should always be truthy since they're not empty strings, so it'll just always be `in_person + " | " + group_session`, unless I'm missing something here

2020-10-30 14:31 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +    // Current it is sent as a single object
slap a "TODO" in there please, and add this task to issue #32

2020-10-30 14:31 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +    }
i'm not 100% sure what's going on with this function since it needs to be updated for when educations is a list but you should be able to combine this and the bottom check into (cont)
```suggestion
    if (educations == null || educations[0] == null ) {
      return <div></div>;
    }
```

2020-10-30 14:31 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +    );
(cont) and then you can remove this check here since you're returning the same thing in both cases. Also is it necessary to return a div or could you just return nothing (null)?

2020-10-30 14:31 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +                ]) /* change this once model supports list of education and remove ternary in getEdu*/
again, pls add these code pointers to #32

2020-10-30 14:31 UTC, chyku commented on frontend/src/utils/api.js
> +      return null;
i mean do they have to return null? or could they just not have a return statement at all

2020-10-30 14:31 UTC, chyku commented on frontend/src/utils/api.js
> +// Endpoint has not been merged to master yet. Remove this once it is
still not sure what this means lol why would this need to be removed? unless you mean the comment needs to be removed

2020-10-30 14:31 UTC, chyku commented on frontend/src/components/pages/Profile.js
>                </span>
has this been tested if a mentor doesn't have a website or linkedin listed?

2020-10-30 16:21 UTC, Leundai commented on frontend/src/utils/api.js
> +// Endpoint has not been merged to master yet. Remove this once it is
I changed it to say remove that specific comment. 👍

2020-10-30 16:48 UTC, Leundai commented on frontend/src/components/pages/Profile.js
>                </span>
Just added that! Question tho.. in the mentor profile they are set as required. Should we change that? 
![image](https://user-images.githubusercontent.com/28935000/97733463-ddeaa300-1aa5-11eb-9ac5-ed49b1656e2f.png)

2020-10-30 22:17 UTC, Leundai commented on frontend/src/utils/api.js
> +      return null;
got it! Realized that it returns undefined anyways without a return

2020-10-30 22:21 UTC, Leundai commented on frontend/src/components/pages/Profile.js
> +      : in_person || group_session;
yoo im big dumb dumb

2020-10-30 22:23 UTC, Leundai commented on frontend/src/components/pages/Profile.js
> +    }
fixed!

2020-10-31 20:54 UTC, chyku approved these changes
lgtm

2020-10-31 20:54 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +            {mentor.phone_number && (
love to see conditional rendering

2020-11-01 15:51 UTC, AngelaLuo49021 approved these changes
Looks good!

2020-11-01 16:18 UTC, merged