Creating Mentor Profile Modal
hack4impact-uiuc/mentee pull request #71
Opened 2020-10-31 02:21 UTC by Lam7150

## Status: :construction: In development

## Description :star2: Implements a modal to edit mentor info

Fixes #24 
## TODOs :star:

2020-11-01 15:48 UTC, AngelaLuo49021 requested changes

2020-11-01 15:48 UTC, AngelaLuo49021 commented on frontend/src/components/pages/Profile.js
> +              <Radio className="modal-availability-radio-text" clicked={inputClicked[3]} index={3} handleClick={handleClick}> Available online? </Radio>
for these 2 buttons. Once you select, you can't unselect them. Also lets change "available online" to "available in person"

2020-11-01 15:48 UTC, AngelaLuo49021 commented on frontend/src/components/pages/Profile.js
> +              <ModalInput height={60} type="dropdown" title="Languages" clicked={inputClicked[7]} index={7} handleClick={handleClick} placeholder="Ex. English, Spanish" options={LANGUAGES}></ModalInp
For both languages and specializations, if you select more than 2 it starts to look wack. Could you make the box bigger as you select more? 
![image](https://user-images.githubusercontent.com/42478474/97807580-401ee180-1c27-11eb-9071-f6bc3025d4cf.png)

2020-11-01 15:48 UTC, AngelaLuo49021 commented on frontend/src/components/pages/Profile.js
> +              <ModalInput type="textarea" title="About" clicked={inputClicked[2]} index={2} handleClick={handleClick}></ModalInput>
why is there a text limit on this?

2020-11-05 23:04 UTC, AngelaLuo49021 requested changes

2020-11-05 23:04 UTC, AngelaLuo49021 commented on frontend/src/components/MentorProfileModal.js
> +const LANGUAGES = ["English", "Spanish", "German", "Chinese", "Vietnamese"]
Can we use the real constants and import them from a constants file since the languages and specializations will be used in multiple places across our application?

Finalized LIsts at bottom of PRD. Please alpha order, thanks! 

https://docs.google.com/document/d/14DHPbMC_1VVO7HG_0sKgJ_gMHOcJxmWx7u0Q4unzbN0/edit

2020-11-05 23:04 UTC, AngelaLuo49021 commented on frontend/src/components/MentorProfileModal.js
> +        // setLanguages(e.target.value)
why do you have functions that do nothing?

2020-11-05 23:04 UTC, AngelaLuo49021 commented on frontend/src/components/MentorProfileModal.js
> +    function handleSpecializationsChange(e) {
same here

2020-11-10 21:28 UTC, AngelaLuo49021 approved these changes
![image](https://user-images.githubusercontent.com/42478474/98735633-533d5a00-2369-11eb-978d-1a443518c103.png)
Dont love this but I also dont want to block this PR bc other ppl need this modal

**EDIT: Resolved!**

2020-11-10 21:59 UTC, chyku submitted a review, later dismissed
nitpicks, looks good otherwise

2020-11-10 21:59 UTC, chyku commented on frontend/package.json
> +}
?? lol

2020-11-10 21:59 UTC, chyku commented on frontend/src/components/MentorProfileModal.js
> +              index={10 + i * 4}
what is this witchery math can u explain in a comment somewhere

2020-11-10 21:59 UTC, chyku commented on frontend/src/components/MentorProfileModal.js
> +  }
for future reference u might be able to just have the entire form input as one state and use the spread operator to edit it but u can leave this as is

2020-11-10 21:59 UTC, chyku commented on frontend/src/components/ModalInput.js
> +function ModalInput(props) {
not sure how many props u got but it's good practice to use object destructuring instead of passing in props, ie. `ModalInput({clicked, onChange, handleClick, ...})` and later you can just call them as `clicked`, `onChange` instead of `props.clicked`, etc

2020-11-10 21:59 UTC, chyku commented on frontend/src/components/css/AntDesign.scss
> +    border-color: #E4BB4F;
rip @nroy20

2020-11-10 21:59 UTC, chyku commented on frontend/src/components/ModalInput.js
> +  const InputBox = (props) => {
same w the props object destructuring thing here

2020-11-10 21:59 UTC, chyku commented on frontend/src/components/css/Profile.scss
> +}
what happened lmao

2020-11-11 22:49 UTC, Lam7150 commented on frontend/package.json
> +}
i have no idea what this is lmao

2020-11-11 22:59 UTC, Lam7150 commented on frontend/src/components/css/AntDesign.scss
> +    border-color: #E4BB4F;
LOL wait what should i change this

2020-11-11 22:59 UTC, Lam7150 commented on frontend/src/components/css/Profile.scss
> +}
i have no idea

2020-11-14 03:28 UTC, Feeshay approved these changes
I’m halfway through a strawberry daiquiri rn so I trust you
Also you can use useState() instead of useState(null) but not sure if that’s preferred

2020-11-14 05:21 UTC, merged