🎨 Responsive design2 (#758)
hack4impact-uiuc/mentee pull request #760
Opened 2023-07-19 03:21 UTC by SolMon9099

* fix mobile design of non admin user pages

http://mentee-dev.herokuapp.com/videos
http://mentee-dev.herokuapp.com/profile
http://mentee-dev.herokuapp.com/gallery/1/626bb8c6a4d6b218a3e62222 http://mentee-dev.herokuapp.com/mentee-appointments http://mentee-dev.herokuapp.com/forgot-password

* front end format

* fix hamburger menu and message page

* front format

* fix message page again

* fix message page again

* fix language switch

## Status:

## Description :star2:

Create Ghost user
 
## TODOs :star:

2023-07-20 09:56 UTC, SolMon9099 commented on frontend/src/features/optionsSlice.js
> +    } catch (error) {}
Yeah, I agree
I added `console.error(error)` and pushed.

2023-07-21 19:36 UTC, Leundai requested changes

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/auth.py
> +            email_verified= True if int(role) == Account.GUEST else False,
Would it be a good idea to keep email verification on for guest accounts? There might be errors in the email Letitia inputs and it might be a good idea to ensure there aren't any fake guest email accounts

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/auth.py
> +            email_verified= True if int(role) == Account.GUEST else False,
plus in` /Login` endpoint we redirect them to verify page the first time they log in

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/auth.py
> +            email_verified= True if int(role) == Account.GUEST else False,
If so we could remove the extra param of role = 0

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/auth.py
> +        if int(role) != Account.ADMIN and int(role) != Account.GUEST:
nit: doing int(role) in` line 162` in order to avoid doing int(role) multiple times

2023-07-21 19:36 UTC, Leundai commented on backend/api/utils/request_utils.py
>  def application_model(role):
I recommend adding the Account.Guest in this if statement block as well. Just in case..

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/admin.py
> +    if int(role) == Account.GUEST:
above: int(role)

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/admin.py
> +            return create_response(data={"message":"This Email is already registered", "status":"fail"})
I looked at the [create_response](https://github.com/hack4impact-uiuc/mentee/blob/4e291cfcb48ed0e7aa04c9ed0f5e700eb26301fa/backend/api/core.py#L27) function and they already have a message parameter that you can directly add instead of putting it as `data={"message": "......"}`

also `"status": "fail"` is not necessary and should instead be returned with a proper [HTTP Response Status Code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/admin.py
> +    return create_response(data={"message":"Add users successfully", "status":"ok"})
ditto on the above comment ^

2023-07-21 19:36 UTC, Leundai commented on backend/api/views/admin.py
> +                return create_response(data={"message":"Can't create firebase user", "status":"fail firebase"})
Same comment applies about the proper way of returning the create_response here:

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/AddGuestModal.js
> +  }, []);
A lot of this code is based off of previous Form creation practices that had a lot of complexity...

I highly highly recommend looking at this [Example](https://github.com/hack4impact-uiuc/mentee/blob/app-updates/frontend/src/components/UpdateTrainingModal.js)

which uses Antd Form components to handle all of this complexity for you

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/AddGuestModal.js
> +  }, []);
I also recommend looking over https://ant.design/components/form

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/AddGuestModal.js
> +      setGuestModalVisible={props.setGuestModalVisible}
I dont think the Modal Component has the prop `setGuestModalVisible`...

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/AddGuestModal.js
> +      footer={<div></div>}
nit: this is can be changed to `null`

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/AddGuestModal.js
> +      {" "}
nit: remove this

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/AddGuestModal.js
> +        <h1>Add Guest User</h1>
nit: I recommend using  Antd Typography instead of `<h1/>`

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/NavHeader.js
> +      return "Guest";
Should this have a t function for translating guest?

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/pages/GuestLogin.js
> +function GuestLogin() {
Optional: Checkout this new login form. It might be useful some parts like the Form component for this 
[LoginForm](https://github.com/hack4impact-uiuc/mentee/blob/app-updates/frontend/src/components/LoginForm.js)

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/pages/SelectLogin.js
> +  isGhost,
Would this be isGuest?

2023-07-21 19:36 UTC, Leundai commented on frontend/src/components/pages/SelectLogin.js
> +              isAdmin ? handleSelect("admin") : handleSelect("guest");
It might be useful to use ACCOUNT_TYPE for "admin" and "guest" instead to avoid using Magic numbers/strings

2023-07-21 19:38 UTC, Leundai commented
Also nit: Please make these PRs as different titles/descriptions. It is really confusing when reusing a previously submitted PR like #758, #760 ... etc

2023-07-21 19:51 UTC, SolMon9099 commented on backend/api/views/admin.py
> +# @admin_only
sorry, I missed it. I have pushed again

2023-07-22 00:58 UTC, SolMon9099 commented
> Also nit: Please make these PRs as different titles/descriptions. It is really confusing when reusing a previously submitted PR like #758, #760 ... etc

I changed the title of this PR

2023-07-22 01:06 UTC, SolMon9099 commented on backend/api/views/admin.py
>      role = request.form["role"]
I changed as your idea.

2023-07-22 01:07 UTC, SolMon9099 commented on backend/api/views/auth.py
> +            email_verified= True if int(role) == Account.GUEST else False,
I changed this part

2023-07-22 01:08 UTC, SolMon9099 commented on backend/api/utils/request_utils.py
>  def application_model(role):
I added Account.Guest in application_model function, too

2023-07-22 01:10 UTC, SolMon9099 commented on frontend/src/components/AddGuestModal.js
> +        <h1>Add Guest User</h1>
I replaced with Antd Typography instead of <h1/>

2023-07-22 01:11 UTC, SolMon9099 commented on frontend/src/components/pages/SelectLogin.js
> +  isGhost,
Sorry, I changed into isGuest

2023-07-22 01:14 UTC, SolMon9099 commented on frontend/src/components/NavHeader.js
> +      return "Guest";
I have added `"guest": "Guest",` in translation.json.
And changed `return "Guest";` into `return t("common.guest");`

2023-07-22 01:14 UTC, SolMon9099 commented on backend/api/views/auth.py
> +        if int(role) != Account.ADMIN and int(role) != Account.GUEST:
I have fixed this part

2023-07-22 01:15 UTC, SolMon9099 commented on backend/api/views/admin.py
> +    if int(role) == Account.GUEST:
I have fixed this part

2023-07-22 01:16 UTC, SolMon9099 commented on frontend/src/components/AddGuestModal.js
> +      setGuestModalVisible={props.setGuestModalVisible}
Sorry, I also think this is an unnecessary part. I removed

2023-07-22 01:16 UTC, SolMon9099 commented on frontend/src/components/AddGuestModal.js
> +      {" "}
removed

2023-07-22 01:25 UTC, SolMon9099 commented on frontend/src/components/AddGuestModal.js
> +      footer={<div></div>}
I removed `setGuestModalVisible={props.setGuestModalVisible}`

2023-07-22 04:30 UTC, SolMon9099 commented on backend/api/views/admin.py
> +            return create_response(data={"message":"This Email is already registered", "status":"fail"})
I have replaced with Response Status Code

2023-07-22 04:32 UTC, SolMon9099 commented on frontend/src/components/AddGuestModal.js
> +  }, []);
I have fixed the workflow of form.

2023-07-23 01:02 UTC, merged