Mentor set appointment blocks
hack4impact-uiuc/mentee pull request #79
Opened 2020-11-03 22:46 UTC by AzureQDragon

## Status:
:construction: In development

## Description :star2:
Adds appointment block creation

Fixes #60 
 
## TODOs :star:
- [ ] Create calendar component
- [ ] Add Modal component
- [ ] Tests
- [ ] Documentation

2020-12-01 21:25 UTC, chyku requested changes
tiny tiny changes but looks good

2020-12-01 21:25 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +  };
so these are very similar, do you think you could add a param for the function for which time it is and just edit times[index][timeindex] instead of having 2 separate functions

2020-12-01 21:25 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +        {console.log(timeSlots)}
get this console log outta here

2020-12-01 21:25 UTC, chyku commented on frontend/src/components/css/AvailabilityCalendar.scss
> +}
did you check if these mess up the edit profile page modal? or if they're the same as lam's scss you can just not include these

2020-12-03 23:17 UTC, chyku requested changes
tiny tiny thing & question

2020-12-03 23:17 UTC, chyku commented on frontend/src/components/css/AvailabilityCalendar.scss
> +    color: #A58123;
can u add the color as a variable to `_app.scss` and then import it here so we can avoid rando hex codes

2020-12-03 23:17 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +                onChange={(event) => handleTimeChange(index, event, 1)}
wait is times[index] not 0 indexed lmao like why is 1 passed as a param into handletimechange instead of 0

2020-12-05 00:12 UTC, chyku requested changes
wtf are these console logs

2020-12-05 00:12 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +        // console.log(set_data.days[i]);
daniel... get this out of here

2020-12-05 00:12 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +    console.log(value.format("YYYY-MM-DD"));
wtf bro

2020-12-05 00:12 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +      for (i = 0; i < set_data.days.length; i++) {
```suggestion
      for (let i = 0; i < set_data.days.length; i++) {
```

2020-12-27 07:09 UTC, AngelaLuo49021 requested changes
- new time appears everytime you start typing for the previous time

https://user-images.githubusercontent.com/42478474/103165553-f691e380-47de-11eb-90c2-66fe94af971b.mov

- when switching year or month, modal pops up for no reason 

https://user-images.githubusercontent.com/42478474/103165644-21306c00-47e0-11eb-8b39-579fc9e98ceb.mov

2020-12-28 03:06 UTC, AngelaLuo49021 approved these changes
beauty

2020-12-28 14:51 UTC, chyku requested changes

2020-12-28 14:51 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +  ];
add this to utils/consts.js please

2020-12-28 14:51 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +    getSetDays();
does it cause issues bc you're not calling getSetDays with Await?

2020-12-28 14:51 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +      }
is there a reason this has to be a for (int i = 0...) loop instead of a foreach? i'm not a huge fan of for loops in javascript

2020-12-28 14:51 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +  const onPanelChange = (value) => {
does the formatter not add a whitespace here wtf lol

2020-12-28 14:51 UTC, chyku commented on frontend/src/components/AvailabilityCalendar.js
> +  };
if you have a function that only calls another function, you can just replace handleCancel calls with setVisible(false)

2020-12-28 14:51 UTC, chyku commented on frontend/src/components/css/AvailabilityCalendar.scss
> +.date-header{
nit but the lack of whitespace here bothers me

2020-12-29 20:24 UTC, AngelaLuo49021 requested changes
One last bug :(
When you set a time for a new date, the green dot does not update automatically. It only updates once you do another movement on the screen.

https://user-images.githubusercontent.com/42478474/103312030-7b4c4f80-49e1-11eb-87c3-05cc0d4a5624.mov

2021-01-02 20:34 UTC, AngelaLuo49021 approved these changes
yay no more bugs

2021-01-05 15:13 UTC, chyku approved these changes

2021-01-06 04:15 UTC, merged