Upload profile picture
hack4impact-uiuc/mentee pull request #80
Opened 2020-11-05 00:51 UTC by Leundai

## Status:

## Description :star2:

Fixes #58 
Using Flask_Imgur which has been added to the utils folder uploading and deleting and the image will now be possible. 
Overall the process is getting the file from the PUT request, fetch the mentor from this PUT request, and update the mentor profile with the given profile image.
 
## Screenshots
![image](https://user-images.githubusercontent.com/28935000/98180936-c9ecda00-1ec7-11eb-9eb2-27f6e4b9fa38.png)
![image](https://user-images.githubusercontent.com/28935000/98183907-c3ae2c00-1ece-11eb-825e-6b5c4f6a1949.png)

## TODOs :star:
- [x] Tests
- [x] Documentation

2020-11-05 20:37 UTC, chyku requested changes

2020-11-05 20:37 UTC, chyku commented on backend/api/views/main.py
> +    if not image_response.get("success", False):
no need to put in `False` if there's no success in the resp since `None` is falsy anyways

2020-11-05 20:37 UTC, chyku commented on backend/api/views/main.py
> +    mentor.picture = image_response["data"]["link"]
can you add functionality that deletes the previous picture from imgur?

2020-11-05 20:59 UTC, Leundai commented on backend/api/views/main.py
> +    mentor.picture = image_response["data"]["link"]
Yeah absolutely, we might need to make Image an embedded document that has both the link and also a hash of the picture
Since the delete function needs that hash to find it

2020-11-05 20:59 UTC, Leundai commented on backend/api/views/main.py
> +    if not image_response.get("success", False):
Sounds good

2020-11-06 00:39 UTC, chyku requested changes

2020-11-06 00:39 UTC, chyku commented on backend/api/utils/request_utils.py
> -    email = StringField(validators=[InputRequired()])
did u mean to delete email lol

2020-11-06 00:39 UTC, chyku commented on backend/api/views/main.py
> +def uploadImage(id):
the route kind of makes it sound like it's the picture id when it's actually the mentor id, maybe mentor/id/image?

also can you consistently use either picture or image lol this is tripping me up

2020-11-12 22:35 UTC, chyku approved these changes
looks fine, just some reminders

2020-11-12 22:35 UTC, chyku commented on backend/api/models/MentorProfile.py
> +    image = EmbeddedDocumentField(Image)
damn we gotta update the db for this then

2020-11-12 22:35 UTC, chyku commented on frontend/src/components/pages/Profile.js
> +        />
might have to tell @Feeshay about this becase he's working on mentee-facing profile page, so this would cause merge conflicts

2020-11-12 22:41 UTC, Leundai commented on backend/api/models/MentorProfile.py
> +    image = EmbeddedDocumentField(Image)
Its all good that is pretty quick to do

2020-11-12 23:21 UTC, AngelaLuo49021 approved these changes
leo is a god

2020-11-16 06:00 UTC, merged