🧒🏻 Docker, pytest and cypress setups
hack4impact-uiuc/mentee pull request #819
Opened 2023-11-14 12:45 UTC by HamzaAnis

## Description :star2:
Docker setup has been changed. Included initial structure of the tests. Docker compose also runs in dev environment with debug enabled
 
## TODOs :star:
Cypress and pytest are configured but github actions workflows need to be configured accordingly

2023-11-14 12:50 UTC, robert-dm requested changes

2023-11-14 12:50 UTC, robert-dm commented on mentee test case/cypress/e2e/pages/HomePage.js
> +        cy.url().should('eq', 'https://mentee-dev.herokuapp.com/')
@HamzaAnis lets please avoid hard coding URLs as we will have another URL for PROD.

2023-11-14 12:50 UTC, robert-dm commented on mentee test case/cypress/e2e/pages/HomePage.js
> +        cy.url().should('eq', 'https://mentee-dev.herokuapp.com/')
@HamzaAnis remove hard coding of URL

2023-11-14 12:50 UTC, robert-dm commented on mentee test case/cypress/e2e/test/ApplyPageTest.cy.js
> +        cy.visit('https://mentee-dev.herokuapp.com/apply')
@HamzaAnis remove hard coding of URL

2023-11-14 12:50 UTC, robert-dm commented on mentee test case/cypress/e2e/test/HomePageTest.cy.js
> +        cy.visit('https://mentee-dev.herokuapp.com/')
@HamzaAnis remove hard coding of URL

2023-11-16 14:51 UTC, HamzaAnis commented on mentee test case/cypress/e2e/test/HomePageTest.cy.js
> +        cy.visit('https://mentee-dev.herokuapp.com/')
Resolved.

2023-11-16 14:51 UTC, HamzaAnis commented on mentee test case/cypress/e2e/test/ApplyPageTest.cy.js
> +        cy.visit('https://mentee-dev.herokuapp.com/apply')
Resolved.

2023-11-16 14:51 UTC, HamzaAnis commented on mentee test case/cypress/e2e/pages/HomePage.js
> +        cy.url().should('eq', 'https://mentee-dev.herokuapp.com/')
Resolved.

2023-11-16 14:51 UTC, HamzaAnis commented on mentee test case/cypress/e2e/pages/HomePage.js
> +        cy.url().should('eq', 'https://mentee-dev.herokuapp.com/')
@robert-dm Resolved.

2023-11-20 18:06 UTC, robert-dm approved these changes

2023-12-29 14:14 UTC, robert-dm approved these changes

2024-01-03 17:20 UTC, robert-dm requested changes
Please remove the two mentioned files @HamzaAnis

2024-01-03 17:20 UTC, robert-dm commented on backend/api/utils/.DS_Store
@HamzaAnis please remove this file

2024-01-03 17:20 UTC, robert-dm commented on backend/api/.DS_Store
@HamzaAnis please remove this file

2024-01-04 12:45 UTC, HamzaAnis commented on backend/api/utils/.DS_Store
It is removed in this PR. It was present on the other branches.

2024-01-04 12:46 UTC, merged