Mentor Portal Videos Page
hack4impact-uiuc/mentee pull request #95
Opened 2020-11-10 22:49 UTC by Leundai

## Status: :construction:

## Description :star2:

Fixes #77 
 
## TODOs :star:
- [ ] Tests
- [ ] Documentation

2020-11-30 02:02 UTC, AngelaLuo49021 approved these changes
Functionality looks good!

2020-12-01 21:43 UTC, chyku requested changes
small things, generally looks good

2020-12-01 21:43 UTC, chyku commented on frontend/src/components/MentorVideo.js
> +  const { onPin, onChangeTag, onDelete } = props;
```suggestion
const MentorVideo = ({ onPin, onChangeTag, onDelete }) => {
```

2020-12-01 21:43 UTC, chyku commented on frontend/src/components/MentorVideo.js
> +          >
would be cool if you could disable the button based on whether it's the pinned vid

2020-12-01 21:43 UTC, chyku commented on frontend/src/components/MentorVideo.js
> +  const { onPin, onChangeTag, onDelete } = props;
you can also add title, tags, date to this

2020-12-01 21:43 UTC, chyku commented on frontend/src/utils/inputs.js
> +export const returnDropdownItems = (items) => {
can you rename this to like formatDropdownItems or something lol i feel like "return" is too literal

2020-12-01 21:43 UTC, chyku commented on frontend/src/components/pages/Videos.js
> +      setFiltered(videosJSON.data.videos);
todo for connecting to backend if someone else is doing it since it would be helpful to provide code pointers for where to do it

2020-12-05 01:08 UTC, chyku requested changes

2020-12-05 01:08 UTC, chyku commented on frontend/src/components/pages/Videos.js
> +      console.log(mentor);
console log!!

2020-12-05 01:14 UTC, chyku approved these changes
good stuff

2020-12-05 01:15 UTC, merged