Add videos for mentee-side mentor profile
hack4impact-uiuc/mentee pull request #98
Opened 2020-11-13 00:05 UTC by Feeshay

## Status:
:construction: In development

## Description :star2:
* Display videos with unique styling for pinned video
* Videos only display if their URL is valid; if it isn't (or if there aren't enough videos), a placeholder is displayed

For example, this user has one pinned video, one regular video, one invalid video:

![image](https://user-images.githubusercontent.com/36244017/99011328-799df980-2511-11eb-8045-849d01fe6071.png)
Resolves #85

2020-11-17 21:45 UTC, chyku approved these changes
looks good except for my one nitpick

2020-11-17 21:45 UTC, chyku commented on frontend/src/components/ProfileVideos.js
>        </Row>
does this have to be hardcoded like this lmao

2020-11-17 22:06 UTC, Feeshay commented on frontend/src/components/ProfileVideos.js
>        </Row>
idk lmao it kinda feels bad

Faith's design has it so that there's only 6 regular videos at a time so this was the easiest way I could think of to do it. 
Not sure if there's something fancy you can do with forEach/map because each row wrapper that needs to be added every 2 videos

2020-11-17 22:24 UTC, AngelaLuo49021 requested changes

2020-11-17 22:24 UTC, AngelaLuo49021 commented on frontend/src/components/ProfileVideos.js
>        </Row>
Mentors should be able to add as many regular videos they need so I think the loop is a good idea. I think the 6 videos was just faith making some placeholders

2020-11-17 22:24 UTC, AngelaLuo49021 commented on frontend/src/components/ProfileVideos.js
>        </Row>
with the loop, you can also remove the placeholder grey blocks and just have a white background

2020-11-19 22:45 UTC, AngelaLuo49021 requested changes
oop one last thing I noticed. Faith has design changes which add the tags of the videos on the bottom
![image](https://user-images.githubusercontent.com/42478474/99733313-9775dc00-2a86-11eb-8383-f04d1fc95532.png)

2020-11-21 15:41 UTC, Leundai reviewed
One thing that I have decided to do for the Mentor's side of video management is putting the pinned video at the top of the list and then it would get stored as such in the Mentor Document in MongoDB. So I'm not sure if @chyku thinks that can be a cool thing to do. It also removes the need to add another field to the video document. Instead, just make the video at index 0 pinned.

2020-11-27 07:05 UTC, AngelaLuo49021 approved these changes
Looks good!

2020-11-30 02:03 UTC, merged