Mentee appointment modal
hack4impact-uiuc/mentee pull request #99
Opened 2020-11-17 06:10 UTC by Lam7150

## Status: :construction: In development

## Description :star2:

Fixes #43 
 
## TODOs :star:

2020-12-03 23:02 UTC, chyku requested changes

2020-12-03 23:02 UTC, chyku commented on frontend/src/components/css/MenteeModal.scss
> +    color: "#7A7A7A";
add colors, consts, to _app.scss

2020-12-05 01:18 UTC, chyku approved these changes
lgtm, few questions abt things

2020-12-05 01:18 UTC, chyku commented on frontend/src/components/MenteeAppointmentModal.js
> +const organizations = ["Hack4Impact", "YMCA"];
wait do you need this? isn't organizations a text box

2020-12-05 01:18 UTC, chyku commented on frontend/src/components/pages/Videos.js
> +function Videos() {}
why lol isn't this gonna cause merge conflicts

2020-12-05 03:54 UTC, Feeshay approved these changes
whooooo

The style consts inside the components feelsbadman but antd be that way

2020-12-05 23:06 UTC, merged